Kubernetes faq etcd quota
ovh/docs pull request #1225
Opened 2021-03-15 10:54 UTC by SebastienJardin

2021-03-16 14:34 UTC, XavierDuthil requested changes
Need work ;)

2021-03-16 14:34 UTC, XavierDuthil commented on pages/cloud/ovhcloud-connect/product.en-asia.md
> +---
You should leave the empty line at the end of each file (probably through your IDE config)

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +---
Don't forget to create the other language files when the review has been fully applied

2021-03-16 14:34 UTC, XavierDuthil commented on pages/cloud/ovhcloud-connect/product.en-ca.md
>  sections: Getting started, Concepts, Configuration, Technical resources
```suggestion
sections: Getting started, Concepts, Configuration, Technical resources, FAQ
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +A lot of customers encounter some trouble with the quota on ETCD allowed disk space.
```suggestion
Some customers might encounter troubles with the quota on ETCD storage usage.
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +## Issues
```suggestion
## Issue
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +When you want to manage an objects into your Kubernetes cluster, you can reached an error like this:
```suggestion
When managing your Kubernetes cluster, you may encounter the following error:
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +For a cluster with 3 servers "b2-7" the quota are : 85MB
```suggestion
For example, a cluster with 3 `b2-7` servers has a quota of 85MB.
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +Don't worry about the decrease, you keep the max quotas allowed forever, to prevent shrink of datas.
```suggestion
The quota can thus be increased by adding nodes, but will never be decreased (even if all nodes are removed) to prevent data loss.
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +## Troubleshoot
```suggestion
## Resolution

The error mentioned above states that the cluster's ETCD storage usage has exceeded the quota.
To resolve the situation, resources created in excess need to be deleted.
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +The formula to calculate ETCD quota allowed is: *Total = 10MB + (25MB per node)*
```suggestion
Each Kubernetes cluster has a dedicated quota on ETCD storage usage,
calculated through the following formula:
*Quota = 10MB + (25MB per node)*
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +The operator cert-manager going to satured all empty allow storage in ETCD.
```suggestion
Most users install cert-manager through Helm, and then move on a bit hastily.

The most common cases of ETCD quota issues come from a bad configuration of [cert-manager](https://cert-manager.io/docs/),
making it continuously create `certificaterequest` resources.

This behaviour will fill the ETCD with resources until the quota is reached.
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +To detect that, you can find the number of certificate-requets:
```suggestion
To detect this situation, you can get the number of `certificaterequest` resources:
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +If you have a huge number of certificate request (+1000 for example), you have find the root cause !
```suggestion
If you have a huge number of certificate requests (+1000 for example), you have found the root cause.
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +To solve that,we propose this way:
```suggestion
To resolve the situation, we propose the following way:
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +* flush all useless certificate request
```suggestion
* Flush all pending certificaterequests
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +* Stop the operator cert-manager
```suggestion
* Stop cert-manager
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +
```suggestion
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +In this case, we don't have a generic solution, but if you have use Helm, we recommend to use Helm for the update.
```suggestion
There is no generic way to do this, but if you use Helm we recommend you to use it for the update.
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +We recommend you to follow the steps for troubleshoot, and ensure all is correctly configured
```suggestion
We recommend you to take the following steps to troubleshoot your cert-manager, and to ensure that everything is correctly configured:
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +* Start the cert-manager operator
```suggestion
* Start cert-manager
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +If cert-manager is not the root causes, you should turn to the other installed operator.
```suggestion
If cert-manager is not the root causes, you should turn to the other running operators.
```

2021-03-16 14:34 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +The way is to find the objects creates by the operator, it is possible the operator create a lots of objects like cert-manager.
```suggestion
We have found that the following resources can sometimes be generated continuously by existing operators:
> backups.velero.io
ingress.networking.k8s.io
ingress.extensions

If that still  does not cover your case, you can use a tool like [ketall](https://github.com/corneliusweig/ketall) to easily list and count resources in your cluster.
```

2021-03-17 09:13 UTC, SebastienJardin commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +---
yep i was waiting the entire doc is review and accepted

2021-03-19 15:43 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/etcd-quota-error/guide.en-gb.md
> +The formula to calculate ETCD quota allowed is: *Total = 10MB + (25MB per node)*
EDIT: We will soon add a max of 200MB to the formula

```suggestion
Each Kubernetes cluster has a dedicated quota on ETCD storage usage,
calculated through the following formula:
*Quota = 10MB + (25MB per node)* (capped to 200MB)
```

2021-03-31 09:10 UTC, SebastienJardin commented on pages/cloud/ovhcloud-connect/product.en-asia.md
> +---
yes I do it on VCS

2021-04-22 17:21 UTC, XavierDuthil commented
During Sebastien's absence, I cloned his branch and updated it, then created the Pull Request https://github.com/ovh/docs/pull/1403. This one can be closed.

2021-04-22 17:21 UTC, closed without merging