[WIP] add: new resources reservec on customers nodes
ovh/docs pull request #1459
Opened 2021-05-06 14:20 UTC by SebastienJardin

2021-05-10 12:12 UTC, ricoleabricot requested changes

2021-05-10 12:12 UTC, ricoleabricot commented on pages/platform/kubernetes-k8s/exposed-apis-software-versions-reserved-resources/guide.en-us.md
> -
why removing the double return line ? It's interpreted by markdown to make a bigger space between blocks

2021-05-10 12:12 UTC, ricoleabricot commented on pages/platform/kubernetes-k8s/exposed-apis-software-versions-reserved-resources/guide.en-us.md
> +Each worker node has GB of RAM and mCPU reserved for Kubernetes components.
You forget the numbers ?
If you want to say it's variable, say something like: a certain amount of

2021-05-10 12:12 UTC, ricoleabricot commented on pages/platform/kubernetes-k8s/exposed-apis-software-versions-reserved-resources/guide.en-us.md
> +To guarantee the availabilty of customers node, we reserverd resources (CPU and RAM), proportionally on the instance flavor.
s/reserverd/are reserving

2021-05-10 12:12 UTC, ricoleabricot commented on pages/platform/kubernetes-k8s/exposed-apis-software-versions-reserved-resources/guide.en-us.md
> +The calcul used to estimed the reservation is :  (10 % of 1 CPU + 0,5% of all CPU cores)
s/estimed/estimate

2021-05-10 12:12 UTC, ricoleabricot commented on pages/platform/kubernetes-k8s/exposed-apis-software-versions-reserved-resources/guide.en-us.md
> +The calcul used to estimed the reservation is : ( (768M Kubernetes + 5% of total memory) + ( 256M system) )
s/estimed/estimate

2021-05-10 12:12 UTC, Kafei59 commented on pages/platform/kubernetes-k8s/exposed-apis-software-versions-reserved-resources/guide.en-us.md
> +The calcul used to estimed the reservation is : ( ( log(total storage)*2 ) + ( log(total storage)*8 ) + ( 10% of total storage ) )
s/estimed/estimate

2021-05-10 12:12 UTC, ricoleabricot commented on pages/platform/kubernetes-k8s/exposed-apis-software-versions-reserved-resources/guide.en-us.md
> +This array helping you to predict resouces available.
s/helping/helps

2021-05-10 12:12 UTC, Kafei59 commented on pages/platform/kubernetes-k8s/exposed-apis-software-versions-reserved-resources/guide.en-us.md
> +This array helping you to predict resouces available.
s/resouces available/available resources

2021-05-10 13:57 UTC, SebastienJardin commented on pages/platform/kubernetes-k8s/exposed-apis-software-versions-reserved-resources/guide.en-us.md
> -
My markdown linter was not happy :/

2021-05-10 13:57 UTC, SebastienJardin commented on pages/platform/kubernetes-k8s/exposed-apis-software-versions-reserved-resources/guide.en-us.md
> +Each worker node has GB of RAM and mCPU reserved for Kubernetes components.
yes, it is variable depending on flavor

2021-05-14 13:37 UTC, Kafei59 approved these changes

2021-05-17 08:20 UTC, tcpdumpfbacke approved these changes

2021-05-17 08:33 UTC, tcpdumpfbacke commented
Thank you for your contribution!

2021-05-17 08:33 UTC, merged