docs: update private registry creation
ovh/docs pull request #1968
Opened 2021-09-23 14:18 UTC by scraly

2021-09-23 14:26 UTC, LostInBrittany approved these changes

2021-09-23 15:29 UTC, OVH-Team-Guides requested changes
Please update the images so that personal information is not displayed. Thanks

2021-09-24 11:51 UTC, scraly commented
@OVH-Team-Guides images fixed

2021-09-27 17:17 UTC, OVH-Team-Guides approved these changes

2021-09-27 17:17 UTC, merged

2021-09-27 17:18 UTC, OVH-Team-Guides commented
Thanks for your contribution @scraly, deployment will be done soon.