Updates, fixes and formatting docs related to the Kubernetes product
ovh/docs pull request #2080
Opened 2021-10-25 12:55 UTC by cortexx

- Add missing warnings related to the billing of resources created in the Kubernetes Managed Service
- Improve formatting
- Add missing information related to the ports list to keep open when security groups are enabled on OpenStack side

2021-10-25 13:48 UTC, XavierDuthil requested changes
I also suggest adding the LB price warning to the https://docs.ovh.com/gb/en/kubernetes/deploying-an-application/ page, which makes the user create a LoadBalancer.

2021-10-25 13:48 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/getting-source-ip-behind-loadbalancer/guide.en-asia.md
> +> By deploying a __Network Load Balancer__ resource in your Managed Kubernetes Service, we will deploy a public Load Balancer allowing routing from the public traffic to your K8s cluster.
```suggestion
> When a __LoadBalancer__ Service resource is created inside a Managed Kubernetes cluster, an associated Public Cloud Load Balancer is automatically created, allowing public access to your K8S application.
```

2021-10-25 13:48 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/getting-source-ip-behind-loadbalancer/guide.en-asia.md
> +> This resource is hourly charged. For more information, please refer to the following documentation: [Network Load Balancer price](https://www.ovhcloud.com/en-ie/public-cloud/prices/#network)
```suggestion
> The Public Cloud Load Balancer service is hourly charged and will appear in your Public Cloud project. For more information, please refer to the following documentation: [Network Load Balancer price](https://www.ovhcloud.com/en-ie/public-cloud/prices/#network)
```

2021-10-25 13:48 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/persistent-volumes-on-ovh-managed-kubernetes/guide.en-au.md
> +> By creating a __Persistent Volumes__ resource in your Managed Kubernetes Service, we will create for you a volume from the __Block Storage__ category.
```suggestion
> When a __Persistent Volumes__ resource is created inside a Managed Kubernetes cluster, an associated Public Cloud __Block Storage__ volume is automatically created with it.
```

2021-10-25 13:48 UTC, XavierDuthil commented on pages/platform/kubernetes-k8s/persistent-volumes-on-ovh-managed-kubernetes/guide.en-au.md
> +> This volume is visible through the OVHcloud Manager and is hourly charged. For more information, please refer to the following documentation: [Volume Block Storage price](https://www.ovhcloud.com/e
```suggestion
> This volume is hourly charged and will appear in your Public Cloud project. For more information, please refer to the following documentation: [Volume Block Storage price](https://www.ovhcloud.com/en-ie/public-cloud/prices/#storage)
```

2021-10-25 14:57 UTC, bs-ovh approved these changes

2021-10-25 16:48 UTC, XavierDuthil approved these changes

2021-10-26 09:39 UTC, merged

2021-10-26 09:39 UTC, OVH-Team-Guides commented
Thanks for your contribution @cortexx and @XavierDuthil. Deployment will be done soon.