Deploy applications to specific Nodes and Nodes Pools (labels and NodeAffinity)
ovh/docs pull request #2300
Opened 2021-12-15 13:40 UTC by scraly

2021-12-15 15:05 UTC, OVH-Team-Guides commented on pages/platform/kubernetes-k8s/label-taint-node-pools/guide.en-asia.md
> +- a [Public Cloud project](https://www.ovhcloud.com/en-gb/public-cloud/) in your OVHcloud account
Please update each website link according to the EN sub. For instance, here the link should be https://www.ovhcloud.com/asia/public-cloud/

2021-12-15 15:06 UTC, OVH-Team-Guides commented on pages/platform/kubernetes-k8s/label-taint-node-pools/guide.en-asia.md
> +- access to the [OVHcloud Control Panel](https://www.ovh.com/auth/?action=gotomanager&from=https://www.ovh.co.uk/&ovhSubsidiary=asia)
The Control Panel links are not ok. The en-asia one should be https://ca.ovh.com/auth/?action=gotomanager&from=https://www.ovh.com/asia/&ovhSubsidiary=asia

2021-12-15 15:07 UTC, OVH-Team-Guides commented on pages/platform/kubernetes-k8s/label-taint-node-pools/guide.en-asia.md
> +Log in to the [OVHcloud Control Panel](https://www.ovh.com/auth/?action=gotomanager&from=https://www.ovh.co.uk/&ovhSubsidiary=asia), go to the `Public Cloud`{.action} section and select the Public Cl
The Control Panel links are not ok. The en-asia one should be https://ca.ovh.com/auth/?action=gotomanager&from=https://www.ovh.com/asia/&ovhSubsidiary=asia

2021-12-15 15:09 UTC, OVH-Team-Guides commented on pages/platform/kubernetes-k8s/label-taint-node-pools/guide.en-asia.md
> +Wait, 'till its status change to `OK`.
suggested change: "Wait until its status changes to `OK`"

2021-12-15 15:10 UTC, OVH-Team-Guides commented on pages/platform/kubernetes-k8s/label-taint-node-pools/guide.en-asia.md
> +Perfect, our two node pools exists and we can see the different configuration and autoscaling mode.
suggested changes: "Our two node pools now exist and we can see the different configuration and autoscaling mode."

2021-12-15 15:11 UTC, OVH-Team-Guides commented on pages/platform/kubernetes-k8s/label-taint-node-pools/guide.en-asia.md
> +And let's display our nodes. You should have 3 nodes running in our first node pool and 1 node in our "hourly" node pool:
suggested changes: "Let's display our nodes.

2021-12-15 15:11 UTC, OVH-Team-Guides commented on pages/platform/kubernetes-k8s/label-taint-node-pools/guide.en-asia.md
> +If you don't do anything during several minutes, the AutoScaling in "hourly" node pool will terminate the node because of innactivity:
inactivity

2021-12-15 15:12 UTC, OVH-Team-Guides commented on pages/platform/kubernetes-k8s/label-taint-node-pools/guide.en-asia.md
> +Perfect!
Please delete.

2021-12-15 15:12 UTC, OVH-Team-Guides commented on pages/platform/kubernetes-k8s/label-taint-node-pools/guide.en-asia.md
> +You have to wait several minutes in order to have a new Node that match with your criterias.
matches

2021-12-15 15:14 UTC, OVH-Team-Guides commented on pages/platform/kubernetes-k8s/label-taint-node-pools/guide.en-asia.md
> +In this tutorial you saw how to create, in your OVHcloud Managed Kubernetes cluster, several kind of node pools and how to deploy your applications easily where we want to.
"In this tutorial you saw how to create, in your OVHcloud Managed Kubernetes cluster, several kind**s** of node pools and how to deploy your applications easily where **you** want to."

2021-12-15 15:15 UTC, OVH-Team-Guides requested changes
Please update all the versions according to the comments left on the en-asia version. To retrieve the correct links (website and control panel), check the Keycloak tutorial versions.

2021-12-16 07:35 UTC, scraly commented
Links are fixed and I follow your remarks, thanks.

About https://www.ovhcloud.com/en-gb/public-cloud/ links, can you add them on https://docs.dsi.ovh/display/CCC/Toolbox#Toolbox-OVHcloudControlPanel(manager)links page?

Thanks

2021-12-16 13:43 UTC, OVH-Team-Guides approved these changes

2021-12-16 16:54 UTC, mhurtrel reviewed
Just before the "We will " section in the"objective" paragraph i would add this sentence to give more context.

The example chosen here will leverage a OVHcloud billing specificity : using monthly billing for nodes that you plan too keep in the long term can decrease your Kubernetes costs by up to 50%.  We see customers with variable workloads create a first node pool with monthly billing to cover their long term compute need, and add elasticity to the cluster with a second node pool using autoscaling and hourly billing.

juste before "## Where do we go from here?" i would also add.

Note that a given label can be applied to multiple node pools and/or to specific nodes only if it makes sense to you.

2021-12-17 07:52 UTC, scraly commented
I just added @mhurtrel additions (and fixed before some tiny spelling mistakes).
Now the PR is ready to be merged :)

2021-12-17 08:01 UTC, merged

2021-12-17 08:01 UTC, OVH-Team-Guides commented
Thanks for your contribution @scraly