feat: Go operator tutorial
ovh/docs pull request #2754
Opened 2022-03-22 09:55 UTC by philippart-s

This tutorial is the continuation of the tutorial [Deploying a Kubernetes Operator based on Helm on OVHcloud Managed Kubernetes](https://docs.ovh.com/gb/en/kubernetes/deploying-helm-operator/)

2022-03-22 11:59 UTC, raclepoulpe commented on pages/platform/kubernetes-k8s/installing-go-operator/guide.en-gb.md
> +
Suggestion: add a link to the doc (https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/) and / or explain what parameters values mean.
example : 
--domain ovhcloud.com is used as the registry Docker Hub namespace
--repo=<path> flag is required when creating a project outside of $GOPATH/src

2022-03-22 13:38 UTC, raclepoulpe commented on pages/platform/kubernetes-k8s/installing-go-operator/guide.en-gb.md
> +
Warning:
If you get an error like:
```bash
bash: /Users/xxxxxxxxx/go-operator/nginx-go-operator/bin/controller-gen: No such file or directory
```
Make sure your GOPATH variable is well defined

2022-03-22 13:55 UTC, raclepoulpe commented on pages/platform/kubernetes-k8s/installing-go-operator/guide.en-gb.md
> +make manifest
make manifests

2022-03-22 13:57 UTC, raclepoulpe commented on pages/platform/kubernetes-k8s/installing-go-operator/guide.en-gb.md
> +Verify that the CRD is updated with the two fields (`port` and `replicaCount`):
Verify that the CRD file **config/crd/bases/tutorials.ovhcloud.com_ovhnginxes.yaml** is updated with the two fields (`port` and `replicaCount`):

2022-03-22 14:02 UTC, philippart-s commented on pages/platform/kubernetes-k8s/installing-go-operator/guide.en-gb.md
> +make manifest
dslé je pensais avoir fait le tour de ce genre de faute ...😨

2022-03-22 14:17 UTC, raclepoulpe commented on pages/platform/kubernetes-k8s/installing-go-operator/guide.en-gb.md
> +
Warning
Don't forget to modify the line
```
tutorialsv1 "github.com/xxxxxxxxxxxxxx/nginx-go-operator/api/v1"
```
 with your own repo in the import block, or you will get an error like:
```
controllers/ovhnginx_controller.go:22:4: no required module provides package github.com/ovhcloud-devrel/nginx-go-operator/api/v1; to add it:
	go get github.com/ovhcloud-devrel/nginx-go-operator/api/v1
Error: not all generators ran successfully
```

2022-04-11 06:55 UTC, scraly requested changes

2022-04-11 06:55 UTC, scraly commented on pages/platform/kubernetes-k8s/installing-go-operator/guide.en-gb.md
> +**Last updated 22th Marsh, 2022.**
March ;-)

2022-04-11 06:55 UTC, scraly commented on pages/platform/kubernetes-k8s/installing-go-operator/guide.en-gb.md
> +An operator is based on a [Custom Resources](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) that allow to extend Kubernetes API.<br>
A voir si la balise `<br>`sera interpretée ou pas au final. 
Juste une remarque, etant donnée que la balise est ouvrante et fermante et ne contient aucun pareamètre, afin qu'elle soit intepretée par tous les navigateurs : `<br/>`qui equivaut a `<br></br>" :-)

2022-04-11 06:59 UTC, scraly requested changes

2022-04-11 06:59 UTC, scraly commented on pages/platform/kubernetes-k8s/installing-go-operator/guide.en-gb.md
> +The GO controller `ovhnginx_controller.go` in the folder `./controllers`:
```suggestion
The Go controller `ovhnginx_controller.go` in the folder `./controllers`:
```

2022-04-11 06:59 UTC, scraly commented on pages/platform/kubernetes-k8s/installing-go-operator/guide.en-gb.md
> +service/ovhnginx-sample   LoadBalancer   10.3.142.85   152.XXX.XXX.209   8080:30946/TCP   3m13s
```suggestion
service/ovhnginx-sample   LoadBalancer   10.3.142.85   XXX.XXX.XXX.XXX   8080:30946/TCP   3m13s
```

2022-04-11 07:25 UTC, philippart-s commented on pages/platform/kubernetes-k8s/installing-go-operator/guide.en-gb.md
> +An operator is based on a [Custom Resources](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) that allow to extend Kubernetes API.<br>
oui je connais mais là ça vient de l'équipe doc ;) qui avait éjouté ces balises sur mon précédent article (même si la remarque est toujours valide ;)

2022-04-11 08:25 UTC, philippart-s commented on pages/platform/kubernetes-k8s/installing-go-operator/guide.en-gb.md
> +service/ovhnginx-sample   LoadBalancer   10.3.142.85   152.XXX.XXX.209   8080:30946/TCP   3m13s
J'ai laissé exprès le début et la fin pour que ce soit plus simple à référencer (c'est déjà le cas dans le reste du tuto et le tuto helm, j'avais vu avec l'équipe doc).
En plus il n'existe plus donc pas de gros risques

2022-04-11 08:55 UTC, philippart-s commented
@scraly & @raclepoulpe si je ne m'abuse j'ai apporté les modifs demandées

2022-04-11 08:56 UTC, scraly approved these changes

2022-04-26 08:22 UTC, merged

2022-04-26 08:22 UTC, OVH-Team-Guides commented
Thanks for your contribution @philippart-s