[ AI Apps ] - Gradio sketch recognition
ovh/docs pull request #3177
Opened 2022-06-23 13:58 UTC by eleapttn

- Documentation for this new tutorial: https://github.com/ovh/ai-training-examples/tree/main/apps/gradio/sketch-recognition
- First tutorial for AI Apps ⚠️ 
- Translation done 🌍

2022-06-23 14:49 UTC, eleapttn commented on pages/platform/ai/app_tuto_01_gradio_sketch_recognition/guide.en-asia.md
> -In order to do this, you will use [Gradio](https://gradio.app/), an open-source Python library which is a quick way to expose and use a Machine Learning models. You will also learn how to build and u
...a Machine Learning **model**.
I think we can remove the S?

2022-06-24 06:57 UTC, philippart-s requested changes
@eleapttn je n'ai regardé que la version anglaise.
Je n'ai pas encore joué les tutos, ce sera ma prochaine étape.

Cela ne reste que des suggestions après une relecture externe 😉

2022-06-24 06:57 UTC, philippart-s commented on pages/platform/ai/app_tuto_01_gradio_sketch_recognition/guide.en-gb.md
> +ref = "Find the whole code [here](ADD github link)."
@eleapttn je pense qu'il manque un lien ici 😉

2022-06-24 06:57 UTC, philippart-s commented on pages/platform/ai/app_tuto_01_gradio_sketch_recognition/guide.en-gb.md
> +The `requirements.txt` file will allow us to write all the modules needed to make our application work. This file will be useful when writing the `Dockerfile`.
Juste une proposition mais pour moi il sert à récupérer / installer plutôt qu'écrire les modules.

```suggestion
The `requirements.txt` file will allow us to get all the modules needed to make our application work. This file will be useful when writing the `Dockerfile`.
```

2022-06-24 06:57 UTC, philippart-s commented on pages/platform/ai/app_tuto_01_gradio_sketch_recognition/guide.en-gb.md
> +Install the `requirements.txt` file which contains your needed Python modules using a `pip install ...` command:
C'est juste une proposition de tournure qui me semble plus juste car ce n'est pas le fichier requirements que l'on installe mais les modules qui sont dans la liste qu'il contient, mais je chipote peut être 😉 

```suggestion
Install your needed Python modules using a `pip install ...` command with the `requirements.txt` file which contains all modules:
```

2022-06-24 06:57 UTC, philippart-s commented on pages/platform/ai/app_tuto_01_gradio_sketch_recognition/guide.en-gb.md
> +Push the compiled image into the shared registry:
Je pense que c'est plus correcte de parler de création d'image que de compilation

```suggestion
Push the created image into the shared registry:
```

2022-06-24 06:57 UTC, philippart-s commented on pages/platform/ai/app_tuto_01_gradio_sketch_recognition/guide.en-gb.md
> +The following command starts a new job running your Gradio application:
Ne serait-ce pas plus judicieux de parler d'app plutôt que de job pour ne pas confondre avec training ?

```suggestion
The following command starts a new app running your Gradio application:
```

2022-06-24 06:57 UTC, philippart-s commented on pages/platform/ai/app_tuto_01_gradio_sketch_recognition/guide.en-gb.md
> +> `--volume <my_saved_model>@<region>/:/workspace/saved_model:RO` is the third volume attached for using your **pretrained model**. This volume is read-only (`RO`) because you just need to use the mo
Pas sûr de comprendre d'où vient la notion de 3ème volume.
Pour moi c'est le premier et seul que l'on attache ?

2022-06-24 07:33 UTC, philippart-s requested changes

2022-06-24 07:33 UTC, philippart-s commented on pages/platform/ai/app_tuto_01_gradio_sketch_recognition/guide.en-asia.md
> +- You also should have followed the steps of the *Image Classification with MNIST dataset* notebook from the [GitHub repository](https://github.com/ovh/ai-training-examples/blob/main/notebooks/comput
@eleapttn je pense qu'il faut rajouter le lien vers le tuto pour expliquer comment créer le notebook et le lancer : https://docs.ovh.com/gb/en/publiccloud/ai/notebooks/tuto-weights-and-biases/

2022-06-24 08:15 UTC, eleapttn commented
guide.en-gb.md updated according to Stephane feedback
duplicata done ✔️

2022-06-24 09:07 UTC, philippart-s approved these changes
🚀

2022-06-24 11:22 UTC, philippart-s requested changes

2022-06-24 11:22 UTC, philippart-s commented on pages/platform/ai/app_tuto_01_gradio_sketch_recognition/guide.en-ca.md
> +docker run --rm -it -p 8080:8080 --user=42420:42420 gradio_app:latest
@eleapttn j'ai une erreur lors du lancement en mode "local", en effet comme on n'a pas de modèle cela génère une erreur :
```bash
gitpod /workspace/ai-training-examples/apps/gradio/sketch-recognition (main) $ docker run --rm -it -p 8080:8080 --user=42420:42420 gradio_app:latest
2022-06-24 09:33:22.679808: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-24 09:33:22.679849: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/workspace/app.py", line 27, in <module>
    model = tf.keras.models.load_model("model/sketch_recognition_numbers_model.h5")
  File "/usr/local/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.7/site-packages/keras/saving/save.py", line 206, in load_model
    raise IOError(f'No file or directory found at {filepath_str}')
OSError: No file or directory found at model/sketch_recognition_numbers_model.h5
```

Du coup soit il faut retirer le lancement local, soit expliquer comment récupérer le modèle ou encore attacher en volume l'obect storage à la commande run.

Mais je me trompe peut être.

2022-06-27 06:38 UTC, eleapttn commented on pages/platform/ai/app_tuto_01_gradio_sketch_recognition/guide.en-ca.md
> +docker run --rm -it -p 8080:8080 --user=42420:42420 gradio_app:latest
done ✔️

2022-06-27 07:53 UTC, philippart-s approved these changes
🚀

2022-06-27 09:21 UTC, merged

2022-06-27 09:22 UTC, OVH-Team-Guides commented
Thanks for your contribution @eleapttn and @philippart-s