Ks sk919 translations changing ph pversion
ovh/docs pull request #3505
Opened 2022-09-28 13:55 UTC by Kazarus4

CCC quality check done
Links checked with gitpod
all translations done

Need proofreading in EN and DE version before PR.

2022-09-28 14:06 UTC, ovh-cds commented
Failed to build static files:
```sh
/tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/plugins/ovh_filters/translator.py:15: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.translations = yaml.load(fd)
/tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/plugins/ovh_filters/banner.py:15: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.banners = yaml.load(fd)
ERROR: Could not process /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/home.it-it.md
  | SyntaxError: invalid syntax (__init__.py, line 151)
CRITICAL: RuntimeError: Error encountered
```

2022-09-28 14:13 UTC, ovh-cds commented
Failed to build static files:
```sh
/tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/plugins/ovh_filters/translator.py:15: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.translations = yaml.load(fd)
/tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/plugins/ovh_filters/banner.py:15: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.banners = yaml.load(fd)
ERROR: Could not process /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/web/domains/api_domain_order/guide.de-de.md
  | SyntaxError: invalid syntax (__init__.py, line 151)
CRITICAL: RuntimeError: Error encountered
```

2022-10-06 14:48 UTC, ovh-cds commented
Failed to build static files:
```sh
{{.cds.build.pelicanoutput}}
```

2022-10-07 06:21 UTC, ovh-cds commented
Failed to build static files:
```sh
/tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/plugins/ovh_filters/translator.py:15: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.translations = yaml.load(fd)
/tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/plugins/ovh_filters/banner.py:15: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.banners = yaml.load(fd)
WARNING: Empty alt attribute for image 3948.png in /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/account/customer/all_about_username/guide.nl-nl.md
WARNING: Empty alt attribute for image 3949.png in /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/account/customer/all_about_username/guide.nl-nl.md
WARNING: Empty alt attribute for image 3936.png in /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/account/customer/all_about_username/guide.nl-nl.md
WARNING: Empty alt attribute for image 3953.png in /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/account/customer/all_about_username/guide.nl-nl.md
WARNING: Other images have empty alt attributes
ERROR: Could not process /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/web/hosting/php_configure_php_on_your_web_hosting_2014/guide.de-de.md
  | ComposerError: expected a single document in the stream
  in "<unicode string>", line 1, column 1:
    title: "PHP-Version eines Webhos ... 
    ^
but found another document
  in "<unicode string>", line 6, column 1:
    --- 
    ^
CRITICAL: RuntimeError: Error encountered
```

2022-10-07 06:48 UTC, ovh-cds commented
Failed to build static files:
```sh
/tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/plugins/ovh_filters/translator.py:15: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.translations = yaml.load(fd)
/tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/plugins/ovh_filters/banner.py:15: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.banners = yaml.load(fd)
WARNING: Empty alt attribute for image 3948.png in /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/account/customer/all_about_username/guide.nl-nl.md
WARNING: Empty alt attribute for image 3949.png in /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/account/customer/all_about_username/guide.nl-nl.md
WARNING: Empty alt attribute for image 3936.png in /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/account/customer/all_about_username/guide.nl-nl.md
WARNING: Empty alt attribute for image 3953.png in /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/account/customer/all_about_username/guide.nl-nl.md
WARNING: Other images have empty alt attributes
ERROR: Could not process /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/web/hosting/php_configure_php_on_your_web_hosting_2014/guide.de-de.md
  | ComposerError: expected a single document in the stream
  in "<unicode string>", line 1, column 1:
    title: "PHP Version eines Webhos ... 
    ^
but found another document
  in "<unicode string>", line 6, column 1:
    --- 
    ^
CRITICAL: RuntimeError: Error encountered
```

2022-10-07 06:58 UTC, ovh-cds commented
Failed to build static files:
```sh
/tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/plugins/ovh_filters/translator.py:15: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.translations = yaml.load(fd)
/tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/plugins/ovh_filters/banner.py:15: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.banners = yaml.load(fd)
WARNING: Empty alt attribute for image 3948.png in /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/account/customer/all_about_username/guide.nl-nl.md
WARNING: Empty alt attribute for image 3949.png in /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/account/customer/all_about_username/guide.nl-nl.md
WARNING: Empty alt attribute for image 3936.png in /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/account/customer/all_about_username/guide.nl-nl.md
WARNING: Empty alt attribute for image 3953.png in /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/account/customer/all_about_username/guide.nl-nl.md
WARNING: Other images have empty alt attributes
ERROR: Could not process /tmp/a6d15caf7e8c9d203af5aa134219bab2/run/docs-rendering/pages/web/hosting/php_configure_php_on_your_web_hosting_2014/guide.de-de.md
  | ComposerError: expected a single document in the stream
  in "<unicode string>", line 1, column 1:
    title: "PHP Version eines Webhos ... 
    ^
but found another document
  in "<unicode string>", line 6, column 1:
    --- 
    ^
CRITICAL: RuntimeError: Error encountered
```

2022-10-07 08:12 UTC, OVH-Team-Guides requested changes

2022-10-07 08:12 UTC, OVH-Team-Guides commented on pages/web/hosting/php_configure_php_on_your_web_hosting_2014/guide.es-es.md
> +## En la práctica
```suggestion
## Procedimiento
```

2022-10-07 08:12 UTC, OVH-Team-Guides commented on pages/web/hosting/php_configure_php_on_your_web_hosting_2014/guide.es-es.md
> +- **Modificando manualmente un archivo en su espacio de almacenamiento** : esta solución es más técnica y necesita estar conectado a su [espacio de almacenamiento FTP](https://docs.ovh.com/es/hosting
```suggestion
- **Modificando manualmente un archivo en su espacio de almacenamiento** : esta solución es más técnica y necesita estar conectado a su [espacio de almacenamiento FTP](https://docs.ovh.com/es/hosting/conexion-espacio-almacenamiento-ftp-alojamiento-web/), donde deberá editar el archivo `.ovhconfig`. Para más información, consulte nuestra guía ["Configurar el archivo .ovhconfig de un alojamiento web"](https://docs.ovh.com/es/hosting/configurar-archivo-ovhconfig/){.external} .
```

2022-10-07 08:12 UTC, OVH-Team-Guides commented on pages/web/hosting/php_configure_php_on_your_web_hosting_2014/guide.es-es.md
> +> Para ello, deberá utilizar obligatoriamente el archivo.`ovhconfig` con ayuda de nuestra documentación ["Configurar el archivo .ovhconfig de mi alojamiento web"](https://docs.ovh.com/es/hosting/conf
```suggestion
> Para ello, deberá utilizar obligatoriamente el archivo `.ovhconfig` con ayuda de nuestra documentación ["Configurar el archivo .ovhconfig de mi alojamiento web"](https://docs.ovh.com/es/hosting/configurar-archivo-ovhconfig/){.external}.
```

2022-10-07 08:12 UTC, OVH-Team-Guides commented on pages/web/hosting/php_configure_php_on_your_web_hosting_2014/guide.es-us.md
> +## En la práctica
```suggestion
## Procedimiento
```

2022-10-07 08:12 UTC, OVH-Team-Guides commented on pages/web/hosting/php_configure_php_on_your_web_hosting_2014/guide.es-us.md
> +- **Modificando manualmente un archivo en su espacio de almacenamiento** : esta solución es más técnica y necesita estar conectado a su [espacio de almacenamiento FTP](https://docs.ovh.com/us/es/host
```suggestion
- **Modificando manualmente un archivo en su espacio de almacenamiento** : esta solución es más técnica y necesita estar conectado a su [espacio de almacenamiento FTP](https://docs.ovh.com/us/es/hosting/conexion-espacio-almacenamiento-ftp-alojamiento-web/), donde deberá editar el archivo `.ovhconfig`. Para más información, consulte nuestra guía ["Configurar el archivo .ovhconfig de un alojamiento web"](https://docs.ovh.com/us/es/hosting/configurar-archivo-ovhconfig/){.external} .
```

2022-10-07 08:12 UTC, OVH-Team-Guides commented on pages/web/hosting/php_configure_php_on_your_web_hosting_2014/guide.es-us.md
> +> Para ello, deberá utilizar obligatoriamente el archivo.`ovhconfig` con ayuda de nuestra documentación ["Configurar el archivo .ovhconfig de mi alojamiento web"](https://docs.ovh.com/us/es/hosting/c
```suggestion
> Para ello, deberá utilizar obligatoriamente el archivo `.ovhconfig` con ayuda de nuestra documentación ["Configurar el archivo .ovhconfig de mi alojamiento web"](https://docs.ovh.com/us/es/hosting/configurar-archivo-ovhconfig/){.external}.
```

2022-10-07 08:12 UTC, OVH-Team-Guides commented on pages/web/hosting/php_configure_php_on_your_web_hosting_2014/guide.pt-pt.md
> +- **alterando manualmente um ficheiro no seu espaço de armazenamento**: esta solução é mais técnica e precisa de aceder ao seu [espaço de armazenamento FTP](https://docs.ovh.com/pt/hosting/aceder-esp
```suggestion
- **alterando manualmente um ficheiro no seu espaço de armazenamento**: esta solução é mais técnica e precisa de aceder ao seu [espaço de armazenamento FTP](https://docs.ovh.com/pt/hosting/aceder-espaco-de-armazenamento-ftp-alojamento-web/) onde deverá modificar o ficheiro `.ovhconfig`. Consulte o nosso manual [Configurar o ficheiro .ovhconfig do alojamento web](https://docs.ovh.com/pt/hosting/configurar-ficheiro-ovhconfig/){.external} para o fazer.
```

2022-10-07 08:17 UTC, OVH-Team-Guides approved these changes

2022-10-07 09:14 UTC, merged