Update Cold Archive guide for Beta release
ovh/docs pull request #3607
Opened 2022-10-19 15:30 UTC by jlutran

2022-10-19 15:41 UTC, Pofilo approved these changes

2022-10-19 16:21 UTC, OVH-Team-Guides requested changes
Please re-integrate the updated canonical link on the following subs: de-de, es-es, es-us, it-it, pl-pl, pt-pt.
Please also apply links changes.

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.de-de.md
> -routes:
Please re-integrate the canonical link on the subs where it's deleted, replacing the link with https://docs.ovh.com/gb/en/storage/object-storage/s3/getting-started-with-cold-archive/

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.de-de.md
> +- [Getting started with AWS CLI](https://docs.ovh.com/gb/en/storage/s3/getting-started-with-s3/#using-the-aws-cli)
```suggestion
- [Getting started with AWS CLI](https://docs.ovh.com/de/storage/object-storage/s3/getting-started-with-object-storage/#using-aws-cli)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.en-asia.md
> +- [Getting started with AWS CLI](https://docs.ovh.com/gb/en/storage/s3/getting-started-with-s3/#using-the-aws-cli)
```suggestion
- [Getting started with AWS CLI](https://docs.ovh.com/asia/en/storage/object-storage/s3/getting-started-with-object-storage/#using-aws-cli)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.en-au.md
> +- [Getting started with AWS CLI](https://docs.ovh.com/gb/en/storage/s3/getting-started-with-s3/#using-the-aws-cli)
```suggestion
- [Getting started with AWS CLI](https://docs.ovh.com/au/en/storage/object-storage/s3/getting-started-with-object-storage/#using-aws-cli)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.en-ca.md
> +- [Getting started with AWS CLI](https://docs.ovh.com/gb/en/storage/s3/getting-started-with-s3/#using-the-aws-cli)
```suggestion
- [Getting started with AWS CLI](https://docs.ovh.com/ca/en/storage/object-storage/s3/getting-started-with-object-storage/#using-aws-cli)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.en-gb.md
>  - [Getting started with AWS CLI](https://docs.ovh.com/gb/en/storage/s3/getting-started-with-s3/#using-the-aws-cli)
```suggestion
- [Getting started with AWS CLI](https://docs.ovh.com/gb/en/storage/object-storage/s3/getting-started-with-object-storage/#using-aws-cli)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.en-ie.md
> +- [Getting started with AWS CLI](https://docs.ovh.com/gb/en/storage/s3/getting-started-with-s3/#using-the-aws-cli)
```suggestion
- [Getting started with AWS CLI](https://docs.ovh.com/ie/en/storage/object-storage/s3/getting-started-with-object-storage/#using-aws-cli)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.en-sg.md
> +- [Getting started with AWS CLI](https://docs.ovh.com/gb/en/storage/s3/getting-started-with-s3/#using-the-aws-cli)
```suggestion
- [Getting started with AWS CLI](https://docs.ovh.com/sg/en/storage/object-storage/s3/getting-started-with-object-storage/#using-aws-cli)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.en-us.md
> +- [Getting started with AWS CLI](https://docs.ovh.com/gb/en/storage/s3/getting-started-with-s3/#using-the-aws-cli)
```suggestion
- [Getting started with AWS CLI](https://docs.ovh.com/us/en/storage/object-storage/s3/getting-started-with-object-storage/#using-aws-cli)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.es-es.md
> +- [Getting started with AWS CLI](https://docs.ovh.com/gb/en/storage/s3/getting-started-with-s3/#using-the-aws-cli)
```suggestion
- [Getting started with AWS CLI](https://docs.ovh.com/es/storage/object-storage/s3/getting-started-with-object-storage/#using-aws-cli)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.es-es.md
> +title: Cold Archive - Getting started with Cold Archive (Beta)
```suggestion
title: Cold Archive - Getting started with Cold Archive (Beta) (EN)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.de-de.md
> +title: Cold Archive - Getting started with Cold Archive (Beta)
```suggestion
title: Cold Archive - Getting started with Cold Archive (Beta) (EN)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.es-us.md
> +title: Cold Archive - Getting started with Cold Archive (Beta)
```suggestion
title: Cold Archive - Getting started with Cold Archive (Beta) (EN)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.es-us.md
> +- [Getting started with AWS CLI](https://docs.ovh.com/gb/en/storage/s3/getting-started-with-s3/#using-the-aws-cli)
```suggestion
- [Getting started with AWS CLI](https://docs.ovh.com/us/es/storage/object-storage/s3/getting-started-with-object-storage/#using-aws-cli)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.fr-ca.md
> +- [Getting started with AWS CLI](https://docs.ovh.com/fr/storage/s3/debuter-avec-s3/#utilisation-de-aws-cli)
```suggestion
- [Getting started with AWS CLI](https://docs.ovh.com/ca/fr/storage/object-storage/s3/getting-started-with-object-storage/#utilisation-de-aws-cli)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.fr-fr.md
>  - [Getting started with AWS CLI](https://docs.ovh.com/fr/storage/s3/debuter-avec-s3/#utilisation-de-aws-cli)
```suggestion
- [Getting started with AWS CLI](https://docs.ovh.com/fr/storage/object-storage/s3/getting-started-with-object-storage/#utilisation-de-aws-cli)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.it-it.md
> +title: Cold Archive - Getting started with Cold Archive (Beta)
```suggestion
title: Cold Archive - Getting started with Cold Archive (Beta) (EN)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.it-it.md
> +- [Getting started with AWS CLI](https://docs.ovh.com/gb/en/storage/s3/getting-started-with-s3/#using-the-aws-cli)
```suggestion
- [Getting started with AWS CLI](https://docs.ovh.com/it/storage/object-storage/s3/getting-started-with-object-storage/#using-aws-cli)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.pl-pl.md
> +title: Cold Archive - Getting started with Cold Archive (Beta)
```suggestion
title: Cold Archive - Getting started with Cold Archive (Beta) (EN)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.pl-pl.md
> +- [Getting started with AWS CLI](https://docs.ovh.com/gb/en/storage/s3/getting-started-with-s3/#using-the-aws-cli)
```suggestion
- [Getting started with AWS CLI](https://docs.ovh.com/pl/storage/object-storage/s3/getting-started-with-object-storage/#using-aws-cli)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.pt-pt.md
> +title: Cold Archive - Getting started with Cold Archive (Beta)
```suggestion
title: Cold Archive - Getting started with Cold Archive (Beta) (EN)
```

2022-10-19 16:21 UTC, OVH-Team-Guides commented on pages/cloud/storage/object_storage/s3_getting_started_with_cold_archive/guide.pt-pt.md
> +- [Getting started with AWS CLI](https://docs.ovh.com/gb/en/storage/s3/getting-started-with-s3/#using-the-aws-cli)
```suggestion
- [Getting started with AWS CLI](https://docs.ovh.com/pt/storage/object-storage/s3/getting-started-with-object-storage/#using-aws-cli)
```

2022-10-19 20:09 UTC, OVH-Team-Guides approved these changes

2022-10-19 20:57 UTC, Pofilo approved these changes

2022-10-20 07:38 UTC, merged

2022-10-20 07:38 UTC, OVH-Team-Guides commented
Thank you for your contribution @jlutran