add paragraph about remote disk impact
ovh/docs pull request #3664
Opened 2022-11-08 09:13 UTC by rgbj

2022-11-08 09:59 UTC, BellionBastien commented on pages/platform/databases/cassandra_01_capabilities/guide.de-de.md
> +Public Cloud Databases will select the most efficient disk type for your cluster depending on your cluster parameters.
Add this link for customer to see in which region which storage technology is available: https://www.ovhcloud.com/en/public-cloud/regions-availability/

2022-11-08 09:59 UTC, BellionBastien commented on pages/platform/databases/cassandra_01_capabilities/guide.de-de.md
> +The type of storage available may vary according to the region your cluster lives in. Thus, your cluster may be backed by e.g. *High Speed* or *High Speed Gen2* block storage.
Add this link for customer to see performance differences between technology: https://www.ovhcloud.com/fr/public-cloud/block-storage/

2022-11-08 15:27 UTC, OVH-Team-Guides requested changes
Hello @rgbj , could you please make all the URLs clickable in all the updated guides ? Thanks

2022-11-08 15:27 UTC, OVH-Team-Guides commented on pages/platform/databases/cassandra_01_capabilities/guide.de-de.md
> +The type of storage available may vary according to the region your cluster lives in: see https://www.ovhcloud.com/en/public-cloud/regions-availability/ for more information about block storage type
```suggestion
The type of storage available may vary according to the region your cluster lives in: see <https://www.ovhcloud.com/en/public-cloud/regions-availability/> for more information about block storage type availability depending on region. Thus, your cluster may be backed by e.g. *High Speed* or *High Speed Gen2* block storage.
```

2022-11-08 15:27 UTC, OVH-Team-Guides commented on pages/platform/databases/cassandra_01_capabilities/guide.de-de.md
> +Also, the performance caracteristics of the various storage offerings may vary depending on e.g. the storage size your cluster uses: *High Speed* may offer better iops than *High Speed Gen2* for some
```suggestion
Also, the performance caracteristics of the various storage offerings may vary depending on e.g. the storage size your cluster uses: *High Speed* may offer better iops than *High Speed Gen2* for some disk sizes. See <https://www.ovhcloud.com/fr/public-cloud/block-storage/> for more information about those performance caracteristics.
```

2022-11-09 08:37 UTC, rgbj commented on pages/platform/databases/cassandra_01_capabilities/guide.de-de.md
> +The type of storage available may vary according to the region your cluster lives in: see https://www.ovhcloud.com/en/public-cloud/regions-availability/ for more information about block storage type
done

2022-11-09 08:37 UTC, rgbj commented on pages/platform/databases/cassandra_01_capabilities/guide.de-de.md
> +Also, the performance caracteristics of the various storage offerings may vary depending on e.g. the storage size your cluster uses: *High Speed* may offer better iops than *High Speed Gen2* for some
done

2022-11-09 08:41 UTC, OVH-Team-Guides approved these changes

2022-11-09 19:02 UTC, merged

2022-11-09 19:02 UTC, OVH-Team-Guides commented
Thank you for your contribution @rgbj