BrenKt-SK864-WEB-Email-Hosted_Exchange-firststep
ovh/docs pull request #4295
Opened 2023-03-02 10:27 UTC by BrenKt

2023-03-02 10:54 UTC, OVH-Team-Guides requested changes

2023-03-02 10:54 UTC, OVH-Team-Guides commented on pages/web/microsoft-collaborative-solutions/exchange_starting_hosted/guide.fr-fr.md
> +- **Configuration manuelle** : Le nom de domaine n'est pas géré dans le même espace client que votre plateforme, il est gérer chez un autre prestataire de nom de domaine, ou vous souhaitez simplement
```suggestion
- **Configuration manuelle** : Le nom de domaine n'est pas géré dans le même espace client que votre plateforme, il est géré chez un autre prestataire de nom de domaine, ou vous souhaitez simplement réaliser votre configuration vous-même.<br> Vous pourrez alors retrouver les valeurs à renseigner à la fin du processus de configuration, ou dans la section `Domaines associés`{.action} de votre plateforme.
```

2023-03-02 10:54 UTC, OVH-Team-Guides commented on pages/web/microsoft-collaborative-solutions/exchange_starting_hosted/guide.fr-fr.md
> +#### **Choisir un nom de domaine**
```suggestion
#### Choisir un nom de domaine
```

2023-03-02 10:54 UTC, OVH-Team-Guides commented on pages/web/microsoft-collaborative-solutions/exchange_starting_hosted/guide.fr-fr.md
> +#### **Allez-vous utiliser uniquement l'offre Exchange OVH avec ce domaine ?**
```suggestion
#### Allez-vous utiliser uniquement l'offre Exchange OVH avec ce domaine ?
```

2023-03-02 10:54 UTC, OVH-Team-Guides commented on pages/web/microsoft-collaborative-solutions/exchange_starting_hosted/guide.fr-fr.md
> +#### **Comment souhaitez-vous configurer votre zone DNS ?**
```suggestion
#### Comment souhaitez-vous configurer votre zone DNS ?
```

2023-03-02 10:54 UTC, OVH-Team-Guides commented on pages/web/microsoft-collaborative-solutions/exchange_starting_hosted/guide.fr-fr.md
> +- Si vous utilisez une offre Exchange seule ou avec d'autres offres **e-mail OVHcloud**, la configuration pourra se faire automatiquement ou manuellement en utilisant uniquement les serveurs e-mail d
```suggestion

- Si vous utilisez une offre Exchange seule ou avec d'autres offres **e-mail OVHcloud**, la configuration pourra se faire automatiquement ou manuellement en utilisant uniquement les serveurs e-mail d'OVHcloud.
```

2023-03-02 10:54 UTC, OVH-Team-Guides commented on pages/web/microsoft-collaborative-solutions/exchange_starting_hosted/guide.fr-fr.md
> +Cette fenêtre vous invite à ajoutez un **champ CNAME** dans la zone DNS du nom de domaine. Cette entrée à pour bute de vérifier que vous gérez bien ce nom de domaine.<br>
```suggestion
Cette fenêtre vous invite à ajouter un **champ CNAME** dans la zone DNS du nom de domaine. Cette entrée a pour but de vérifier que vous gérez bien ce nom de domaine.<br>
```

2023-03-02 10:54 UTC, OVH-Team-Guides commented on pages/web/microsoft-collaborative-solutions/exchange_starting_hosted/guide.fr-fr.md
> +- Si vous configurez votre plateforme Exchange avec un nom de domaine qui n'est pas géré sur le même espace client que cette plateforme, qu'il est géré chez un autre prestataire de nom de domaine, ou
```suggestion
- Si vous configurez votre plateforme Exchange avec un nom de domaine qui n'est pas géré sur le même espace client que cette plateforme, qu'il est géré chez un autre prestataire de nom de domaine, ou si vous avez choisi de configurer manuellement votre nom de domaine, la fenêtre suivante s'affichera :<br>
```

2023-03-02 10:54 UTC, OVH-Team-Guides commented on pages/web/microsoft-collaborative-solutions/exchange_starting_hosted/guide.fr-fr.md
> +Vous retrouvez ici les valeurs à renseigner dans votre zone DNS. les **champs MX** qui correspondent à la réception de vos e-mails et le **champ SRV** qui correspond à la configuration automatique de
```suggestion
Vous retrouvez ici les valeurs à renseigner dans votre zone DNS. Les **champs MX** correspondent à la réception de vos e-mails. Le **champ SRV** correspond à la configuration automatique de vos adresses e-mail.
```

2023-03-02 10:54 UTC, OVH-Team-Guides commented on pages/web/microsoft-collaborative-solutions/exchange_starting_hosted/guide.fr-fr.md
> +Retrouvez les détails de configuration de votre zone DNS concernant votre service e-mail sur notre page [Ajouter un champ MX à la configuration de son nom de domaine](https://docs.ovh.com/fr/domains/
```suggestion
Retrouvez les détails de configuration de votre zone DNS concernant votre service e-mail sur notre page « [Ajouter un champ MX à la configuration de son nom de domaine](https://docs.ovh.com/fr/domains/mail-mutualise-guide-de-configuration-mx-avec-zone-dns-ovh/) ».
```

2023-03-02 10:54 UTC, OVH-Team-Guides commented on pages/web/microsoft-collaborative-solutions/exchange_starting_hosted/guide.fr-fr.md
> +Une fois la première configuration de votre domaine terminée, vous pouvez également configurer des noms de domaines additionnels si vous le souhaitez et si vous ne l'avez pas déjà fait, via l'assista
```suggestion
Une fois la première configuration de votre domaine terminée, vous pouvez également configurer, via l'assistant, des noms de domaines additionnels si vous le souhaitez et si vous ne l'avez pas déjà fait.
```

2023-03-02 10:54 UTC, OVH-Team-Guides commented on pages/web/microsoft-collaborative-solutions/exchange_starting_hosted/guide.fr-fr.md
> +> Toutes les adresses créées sur votre service Exchange seront visible dans l'annuaire des adresses de ce service, y compris celles possédant un nom de domaine différent. Pour dissocier l'affichage d
```suggestion
> Toutes les adresses créées sur votre service Exchange seront visibles dans l'annuaire des adresses de ce service, y compris celles possédant un nom de domaine différent. Pour dissocier l'affichage des domaines, vous devez commander un nouveau service Hosted Exchange pour le ou les noms de domaine concernés.
```

2023-03-02 10:54 UTC, OVH-Team-Guides commented on pages/web/microsoft-collaborative-solutions/exchange_starting_hosted/guide.fr-fr.md
> +OVHcloud propose des licences Outlook en option avec votre compte e-mail Exchange depuis l'[espace client OVHcloud](https://www.ovh.com/auth/?action=gotomanager&from=https://www.ovh.com/fr/&ovhSubsid
```suggestion
OVHcloud propose des licences Outlook en option avec votre compte e-mail Exchange depuis l'[espace client OVHcloud](https://www.ovh.com/auth/?action=gotomanager&from=https://www.ovh.com/fr/&ovhSubsidiary=fr){.external}. 
Pour y souscrire, consultez notre page « [Obtenir une licence Outlook pour Exchange](https://docs.ovh.com/fr/microsoft-collaborative-solutions/exchange-licence-outlook-exchange-2013/) ». 
```

2023-03-06 16:52 UTC, OVH-Team-Guides approved these changes

2023-03-06 16:56 UTC, ovh-cds commented
Failed to build static files:
```sh
{{.cds.build.pelicanoutput}}
```

2023-03-06 17:18 UTC, merged