AI Deploy : new tutorial
ovh/docs pull request #4436
Opened 2023-03-29 13:13 UTC by baaastijn

new tutorial
can be prodded asap

2 notes : 
a 30x redirect is ongoing for this url, i will ask for a removal 
Also, order = 0 is normal, to be on the top

2023-03-29 14:52 UTC, tcpdumpfbacke requested changes

2023-03-29 14:52 UTC, tcpdumpfbacke commented on pages/platform/ai/deploy_tuto_12_build_custom_image/guide.en-gb.md
> +The most popular open source frameworks for exposing APIs are [Flask]() and [Fast API]().
Links missing here :]

2023-03-30 07:24 UTC, tcpdumpfbacke approved these changes

2023-03-30 09:00 UTC, merged

2023-03-30 09:00 UTC, OVH-Team-Guides commented
Thank you for your contribution @baaastijn