Mb ai notebooks img seg tuto
ovh/docs pull request #4500
Opened 2023-04-13 13:27 UTC by MathieuBsqt

Here is a new tutorial about image segmentation for AI Notebooks. 

- I have create all language duplicas & updated the index file. 

*This PR will be in draft until the notebook link is available. I need to add it in the docs.*

2023-04-14 14:14 UTC, tcpdumpfbacke commented on pages/platform/ai/notebook_tuto_12_image-segmentation-unet-tumors/guide.de-de.md
> +excerpt: How to convert Speech to Text using AI Notebooks
Please fix in all files concerned. :)

2023-04-17 09:48 UTC, eleapttn requested changes

2023-04-17 09:48 UTC, eleapttn commented on pages/platform/ai/notebook_tuto_12_image-segmentation-unet-tumors/guide.en-gb.md
> +
I would have probably added:
`- a Kaggle account`

2023-04-17 09:48 UTC, eleapttn commented on pages/platform/ai/notebook_tuto_12_image-segmentation-unet-tumors/guide.en-gb.md
> +A preview of this notebook can be found on GitHub [here](####PUT LINK ONCE AVAILABLE####).
```suggestion
A preview of this notebook can be found on GitHub [here](https://github.com/ovh/ai-training-examples/blob/main/notebooks/computer-vision/image-segmentation/tensorflow/brain-tumor-segmentation-unet/notebook_image_segmentation_unet.ipynb).
```

2023-04-17 09:48 UTC, eleapttn commented on pages/platform/ai/notebook_tuto_12_image-segmentation-unet-tumors/guide.en-gb.md
> +## Go further
```suggestion
## Go further

```

2023-04-17 12:41 UTC, MathieuBsqt commented
Thanks for your feedbacks ! 
Now Ready to merge

2023-04-17 13:52 UTC, eleapttn approved these changes

2023-04-17 13:53 UTC, eleapttn approved these changes

2023-04-19 12:09 UTC, tcpdumpfbacke approved these changes

2023-04-19 12:48 UTC, merged

2023-04-19 12:55 UTC, OVH-Team-Guides commented
Thank you for your contribution @MathieuBsqt