Update Managed Private Registry FAQ documentation to add region dependencies
ovh/docs pull request #4541
Opened 2023-04-25 09:19 UTC by thcdrt

Hello,

I updated Managed Private Registry documentation add the new region availability (BHS) and add a dependencies table.

Thomas

2023-04-25 09:22 UTC, scraly requested changes

2023-04-25 09:22 UTC, scraly commented on pages/platform/private-registry/managed-private-registry-faq/guide.de-de.md
> +### What are the Managed Private Registry service dependencies ?
```suggestion
### What are the Managed Private Registry service dependencies?
```

2023-04-25 14:58 UTC, scraly approved these changes

2023-04-26 09:06 UTC, merged

2023-04-26 09:06 UTC, OVH-Team-Guides commented
Thank you for your contribution @thcdrt