FP SK1236 - Fix nova
ovh/docs pull request #5332
Opened 2023-10-27 08:42 UTC by fpillotovh

2023-10-27 09:22 UTC, yomovh commented on pages/public_cloud/compute/prepare_the_environment_for_using_the_openstack_api/guide.en-gb.md
Python >=3.8 is required (see https://pypi.org/project/python-openstackclient/)

2023-10-27 09:30 UTC, yomovh requested changes
See comments : 2 things to update (python version on Windows + links to https://docs.openstack.org/

additionally, please add something like : 

if you need to configure the Public Cloud Load Balancer you will to run : 

pip3 install python-octaviaclient

Thanks

2023-10-27 09:30 UTC, yomovh commented on pages/public_cloud/compute/loading_openstack_environment_variables/guide.en-gb.md
Remove the /train that points to an old release

2023-11-03 10:20 UTC, yomovh approved these changes
OK for me

2023-11-09 09:23 UTC, tcpdumpfbacke approved these changes
rdy

2023-11-16 12:47 UTC, BrenKt commented on pages/public_cloud/compute/prepare_the_environment_for_using_the_openstack_api/guide.fr-fr.md
> +To configure the Public Cloud Load Balancer you will need to install the Python Octavia client:
```suggestion
Pour configurer le Load Balancer Public Cloud , vous devez installer le client Python Octavia :
```

2023-11-21 08:50 UTC, BrenKt reviewed
ok

2023-11-24 12:54 UTC, BrenKt approved these changes

2023-11-28 10:41 UTC, tcpdumpfbacke commented
Thank you @fpillotovh !

2023-11-28 10:42 UTC, merged