All Languages - update Template S3 Terraform Backend - pages/public_c…
ovh/docs pull request #5431
Opened 2023-11-25 11:48 UTC by Mx7ca

…loud/compute/use_object_storage_terraform_backend_state

This PR fixes https://github.com/ovh/docs/issues/5430 in the documentation of all existing languages.

2023-11-27 08:35 UTC, scraly approved these changes
Top, thank you!

2023-11-27 08:42 UTC, scraly commented
Thanks for the PR, I will update it to add the information for old terraform version

2023-11-27 08:43 UTC, scraly requested changes
add compatibility with old version

2023-11-27 09:03 UTC, scraly commented
The modification will only work for new version, not old version. 

Please add this change:


Before terraform version 1.6.0:

```yaml
terraform {
    backend "s3" {
      bucket = "terraform-state-hp"
      key    = "terraform.tfstate"
      region = "gra"
 #or sbg or any activated high performance storage region
      endpoint = "s3.gra.perf.cloud.ovh.net"
      skip_credentials_validation = true
      skip_region_validation = true
    }
}
```

After terraform version 1.6.0:

```yaml
terraform {
    backend "s3" {
      bucket = "terraform-state-hp"
      key    = "terraform.tfstate"
      region = "gra"
      # sbg or any activated high performance storage region
      endpoints = {
        s3 = "https://s3.gra.perf.cloud.ovh.net/"
      }
      skip_credentials_validation = true
      skip_region_validation      = true
      skip_requesting_account_id  = true
    }
}
```

```

2023-11-27 09:15 UTC, scraly commented
FYI the information about the terraform version is in the hashicorp doc:
https://developer.hashicorp.com/terraform/language/upgrade-guides#s3-backend

2023-11-30 15:37 UTC, Mx7ca commented
@scraly thanks for the link to [OVH's documentation](https://developer.hashicorp.com/terraform/language/upgrade-guides#s3-backend). I've updated the version restriction to all files and also updated the "updated" date again.
Is it now okay?

2023-12-04 09:55 UTC, scraly commented
Thanks, it's good for me :-) 

The only thing to change is the date of the modification :)

2023-12-04 09:55 UTC, scraly approved these changes

2023-12-04 10:06 UTC, OVH-Team-Guides commented on pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.de-de.md
> +updated: 2023-11-30
```suggestion
updated: 2023-12-04
```
@Mx7ca , could you please update this date on all the versions ? Thank you

2023-12-06 14:21 UTC, OVH-Team-Guides commented on pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.de-de.md
> +updated: 2023-11-30
We will do it on our side

2023-12-06 14:21 UTC, merged

2023-12-06 14:21 UTC, OVH-Team-Guides commented
Thank you for your contribution @Mx7ca