octavia monitoring prometheus
ovh/docs pull request #5496
Opened 2023-12-07 08:41 UTC by fpillotovh

2023-12-11 16:13 UTC, yomovh requested changes
See comments

2023-12-11 16:13 UTC, yomovh commented on pages/public_cloud/public_cloud_network_services/technical-resources-02-octavia-monitoring-prometheus/guide.en-gb.md
> +> [!primary]
To be removed. This part of the documentation is for the administrators (OVHCloud) , not for the end user

2023-12-11 16:13 UTC, yomovh commented on pages/public_cloud/public_cloud_network_services/technical-resources-02-octavia-monitoring-prometheus/guide.fr-fr.md
I thought we do not provide anymore french for new public cloud guides ?

2023-12-11 16:13 UTC, yomovh commented on pages/public_cloud/public_cloud_network_services/technical-resources-02-octavia-monitoring-prometheus/meta.yaml
Octavia is not the name of product, please remove it from the slug and use the official name : public cloud load balancer.

2023-12-11 16:13 UTC, yomovh commented on pages/index.md
Please use the official product name "Public Cloud Load Balancer" not octavia

2023-12-22 10:26 UTC, merged

2023-12-22 10:27 UTC, OVH-Team-Guides commented
Thank you for your contribution @fpillotovh