KevS-YC-Translation-shared-responsibility-SAP-solution-for-OVHcloud
ovh/docs pull request #5510
Opened 2023-12-08 13:57 UTC by Kazarus4

EN translation of RACI based on FR version. asked by @Y0Coss

2023-12-08 16:18 UTC, mlt-ovh requested changes

2023-12-08 16:18 UTC, mlt-ovh commented on pages/hosted_private_cloud/sap_on_ovhcloud/sap_raci/guide.en-gb.md
> +The RACI below details the division of responsibilities between OVHcloud and the customer for SAP on OVHcloud solutions. This model can help the customer get the most out of SAP on OVHcloud solutions
RACI "Dedicated Servers" =>"Dedicated Servers" RACI
RACI "VMware on OVHcloud" =>  "VMware on OVHcloud" RACI

2023-12-08 16:18 UTC, mlt-ovh commented on pages/hosted_private_cloud/sap_on_ovhcloud/sap_raci/guide.en-gb.md
> +| X | X | Choose to subscribe to the [Dedicated Server](/pages/account_and_service_management/responsibility_sharing/dedicated-servers) service  or [VMware on OVHcloud](/pages/hosted_private_cloud/ho
Dedicated Server service or VMware on OVhcloud service
(more clear if we repeat the word "service I think")

2023-12-08 16:18 UTC, mlt-ovh commented on pages/hosted_private_cloud/sap_on_ovhcloud/sap_raci/guide.en-gb.md
> +| X | X | You must own the license rights for the SAP software deployed on the infrastructure | RA |  |
Why "you must" ? => only "Own" no ?

2023-12-08 16:18 UTC, mlt-ovh commented on pages/hosted_private_cloud/sap_on_ovhcloud/sap_raci/guide.en-gb.md
> +| X | X | Provision of the subscribed service and available features (OVHcloud Backint Agent for SAP HANA, OS image SLES4SAP BYOL) | I | RA |
Provision the (without "of") ?

2023-12-08 16:18 UTC, mlt-ovh commented on pages/hosted_private_cloud/sap_on_ovhcloud/sap_raci/guide.en-gb.md
> +|  | X | Provision of the subscribed service and available features (Terraform modules for deploying SAP infrastructure as code, SAP HANA pre-installation) | I | RA |
Provision the (without "of") ?

2023-12-08 16:18 UTC, mlt-ovh commented on pages/hosted_private_cloud/sap_on_ovhcloud/sap_raci/guide.en-gb.md
> +|  | X | Choosing to launch the deployment of SAP infrastructure as code | RA |  |
Choose

2023-12-08 16:18 UTC, mlt-ovh commented on pages/hosted_private_cloud/sap_on_ovhcloud/sap_raci/guide.en-gb.md
> +| X | X | Analyzing and correcting proven development issues (bugs, faults, etc.) of the 'OVHcloud Backint Agent' | I | RA |
Analyze and correct

2023-12-08 16:18 UTC, mlt-ovh commented on pages/hosted_private_cloud/sap_on_ovhcloud/sap_raci/guide.en-gb.md
> +| X | X | Handle incidents related to the SLES4SAP OS in BYOL mode and open tickets with the SUSE publisher if necessary | RA |  |
SUSE company (not publisher)

2023-12-12 12:00 UTC, OVH-Team-Guides commented on pages/hosted_private_cloud/sap_on_ovhcloud/sap_raci/guide.en-gb.md
> +|  | X | Provision of the subscribed service and available features (Terraform modules for deploying SAP infrastructure as code, SAP HANA pre-installation) | I | RA |
@mlt-ovh , I suggest either "Provision of" or Provide the" (my preference is the 2nd choice)

2023-12-12 12:00 UTC, OVH-Team-Guides commented on pages/hosted_private_cloud/sap_on_ovhcloud/sap_raci/guide.en-gb.md
> +| X | X | Provision of the subscribed service and available features (OVHcloud Backint Agent for SAP HANA, OS image SLES4SAP BYOL) | I | RA |
@mlt-ovh , I suggest either "Provision of" or Provide the" (my preference is the 2nd choice)

2023-12-13 14:57 UTC, mlt-ovh commented on pages/hosted_private_cloud/sap_on_ovhcloud/sap_raci/guide.en-gb.md
> +|  | X | Provision of the subscribed service and available features (Terraform modules for deploying SAP infrastructure as code, SAP HANA pre-installation) | I | RA |
Ok for me

2023-12-13 14:58 UTC, mlt-ovh commented on pages/hosted_private_cloud/sap_on_ovhcloud/sap_raci/guide.en-gb.md
> +| X | X | Provision of the subscribed service and available features (OVHcloud Backint Agent for SAP HANA, OS image SLES4SAP BYOL) | I | RA |
Ok for me

2023-12-14 09:01 UTC, OVH-Team-Guides commented
@mlt-ovh , we applied your suggestions and did some minor edits. Can you please review again?

2023-12-14 09:28 UTC, mlt-ovh approved these changes

2023-12-14 10:31 UTC, merged