feat(dedicated/api-os-installation): add new page
ovh/docs pull request #5760
Opened 2024-02-02 14:37 UTC by JayBeeDe

ref: PUBM-35205

2024-02-02 14:41 UTC, JayBeeDe commented on pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-gb.md
> +
@YoannAtOVH  comme tu peux le constater, j'en ai profité pour rajouter les liens manquants

2024-02-02 14:41 UTC, JayBeeDe commented on pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.en-gb.md
> +
@YoannAtOVH  comme tu peux le constater, j'en ai profité pour rajouter les liens manquants

2024-02-02 14:46 UTC, JayBeeDe commented
I think the following existing page:
- URL: https://help.ovhcloud.com/csm/en-gb-dedicated-servers-install-hybrid?id=kb_article_view&sysparm_article=KB0043594
- title: Choosing the disk group to install an operating system / Choisir une grappe de disques pour installer un système d’exploitation
- excerpt: Learn here how to choose a disk group to install your operating system / Découvrez comment choisir une grappe de disques spécifique pour installer votre système d'exploitation
should be removed and redirected to that new page (later, once this PR si merged/deployed) because:
- it contains screenshot of the console (content is too static and old-dated) rather than link to the API
- no one will never search "grappe" or "disk group" in Google
- it's included in that page

2024-02-02 17:39 UTC, sbraz requested changes
First page reviewed
EDIT: oh cool the rest is just URL changes :)

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-gb.md
> +In the response, look at the sub-hash `ovh`: this is the list of OSes in the OVHcloud catalog that you can install on this server.
Do people (I mean besides Perl developers) really call things hashes?
```suggestion
In the response, look at the contents of the `ovh` key: this is the list of OSes in the OVHcloud catalog that you can install on this server.
```

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-gb.md
> +¹ Customers that don't use images from OVHcloud catalog (installation from a custom image ([BYOI](/pages/bare_metal_cloud/dedicated_servers/bring-your-own-image)/[BYOLinux](/pages/bare_metal_cloud/de
```suggestion
¹ Customers that don't use images from the OVHcloud catalogue (installation from a custom image ([BYOI](/pages/bare_metal_cloud/dedicated_servers/bring-your-own-image)/[BYOLinux](/pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux)), installation over the network, or manually via IPMI) are not affected by this limitation.<br />
```
* catalogue is the british spelling and this is the GB file
* "the" should be added to all English variants

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-gb.md
> +> If you need to have all those informations for all available OSes in the catalog, you should consider using the API call `/dedicated/installationTemplate/templateInfos`{.action} instead.
```suggestion
> If you need to see this information for all available OSes in the catalog, you should consider using the API call `/dedicated/installationTemplate/templateInfos`{.action} instead.
```

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-gb.md
> +Some OSes can have a list of specific questions. If that's the case, attribute `inputs` contains a list of questions.
```suggestion
Some OSes can have a list of specific questions. If that is the case, the `inputs` key contains a list of questions.
```
Not sure we should call it key or attribute though

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-gb.md
> +¹ If a mandatory question without default value is not answered, API will return an error.
```suggestion
¹ If a mandatory question without default value is not answered, the API will return an error.
```

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-gb.md
> +Some [dedicated servers](https://www.ovhcloud.com/fr/bare-metal/) have multiple groups of disks; For example a group with SATA disks and a group with SSD disks. Those servers are sometimes also calle
```suggestion
Some [dedicated servers](https://www.ovhcloud.com/fr/bare-metal/) have multiple groups of disks; for example one group with SATA disks and another group with SSD disks. Those servers are sometimes also called **hybrid servers**.
```

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-gb.md
> +When you have gathered all informations that you need, you can create the OS installation task with the following API call:
```suggestion
When you have gathered all the information that you need, you can create the OS installation task with the following API call:
```

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-gb.md
> +`userMetadata` contains a list of key/value with the answers to the OS specific questions:
```suggestion
`userMetadata` contains a list of key/value with the answers to the OS-specific questions:
```

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-gb.md
> +Payload example to install Windows Server 2022 Standard (Core) in french:
```suggestion
Payload example to install Windows Server 2022 Standard (Core) in French:
```

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-gb.md
> +    "customHostname": "ma-fenetre"
:rofl:

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-gb.md
> +Example of reply:
```suggestion
Example reply:
```

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-gb.md
> +`123456789` is the OS installation task id. You can follow the OS installation task status with the following API call:
```suggestion
`123456789` is the OS installation task ID. You can follow the OS installation task status with the following API call:
```

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-gb.md
> +You can also see a detailed progress of each step of the installation process, with the following API call:
```suggestion
You can also monitor the progress of the installation process with the following API call which displays a detailed list of steps:
```
Something like this?

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.fr-fr.md
> +Il peut être intéressant d'automatiser l'installation d'un système d'exploitation ou la re-installation d'un système d'exploitation de vos [serveurs dédiés](https://www.ovhcloud.com/fr/bare-metal/) à
```suggestion
Il peut être intéressant d'automatiser l'installation d'un système d'exploitation ou la réinstallation d'un système d'exploitation de vos [serveurs dédiés](https://www.ovhcloud.com/fr/bare-metal/) à l'aide de l'[API OVHcloud](https://api.ovh.com/).
```

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.fr-fr.md
> +Vous pouvez lister les OS compatibles pour un serveur donné, en utilisant l'appel suivant :
```suggestion
Vous pouvez lister les OS compatibles pour un serveur donné en utilisant l'appel suivant :
```

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.fr-fr.md
> +Regardez la liste retournée pour le paramètre `ovh`{.action} : il s'agit de la liste des OS du catalogue OVHcloud que vous pouvez installer.
```suggestion
Regardez la liste retournée sous la clef `ovh`{.action} : il s'agit de la liste des OS du catalogue OVHcloud que vous pouvez installer.
```

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.fr-fr.md
> +¹ Les clients n'utilisant pas les images du catalogue OVHcloud (installation via une image personnalisée ([BYOI](/pages/bare_metal_cloud/dedicated_servers/bring-your-own-image)/[BYOLinux](/pages/bare
```suggestion
¹ Les clients n'utilisant pas les images du catalogue OVHcloud (installation via une image personnalisée ([BYOI](/pages/bare_metal_cloud/dedicated_servers/bring-your-own-image)/[BYOLinux](/pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux)), installation par le réseau, ou  manuellement avec l'IPMI) ne sont pas concernés par cette limitation.<br />
```

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.fr-fr.md
> +Certains OS peuvent avoir une liste de questions spécifiques. Si c'est le cas, l'attribut `inputs`{.action} contient une liste de questions.
```suggestion
Certains OS peuvent avoir une liste de questions spécifiques. Si c'est le cas, la clef `inputs`{.action} contient une liste de questions.
```

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.fr-fr.md
> +Certains OS peuvent avoir une liste de questions spécifiques. Si c'est le cas, l'attribut `inputs`{.action} contient une liste de questions.
Même remarque qu'en anglais : peut-être qu'il faut mettre "clef" partout au lieu d'"attribut" ?

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.fr-fr.md
> +¹ Si une question obligatoire ne possédant pas de valeur par défaut n'est pas répondue, alors l'API va retourner une erreur.
```suggestion
¹ Si une question obligatoire ne possédant pas de valeur par défaut est laissée sans réponse, alors l'API retournera une erreur.
```

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.fr-fr.md
> +- la première (diskGroupId=1) contient 2 disques de 480 Go chaque,
```suggestion
- la première (diskGroupId=1) contient 2 disques de 480 Go chacun,
```

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.fr-fr.md
> +- la seconde (diskGroupId=2) contient 2 disques de 1,9 To chaque.
```suggestion
- la seconde (diskGroupId=2) contient 2 disques de 1,9 To chacun.
```

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.fr-fr.md
> +`userMetadata`{.action} constitue une liste de clés/valeurs qui contient les réponses aux questions :
```suggestion
`userMetadata`{.action} contient une liste de clés/valeurs donnant les réponses aux questions :
```

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.fr-fr.md
> +Regardez la liste retournée pour le paramètre `ovh`{.action} : il s'agit de la liste des OS du catalogue OVHcloud que vous pouvez installer.
Ou « clé », je vois que tu as cette orthographe ailleurs.

2024-02-02 17:39 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.fr-fr.md
> +`123456789` correspond à l'identifiant de la tâche d'installation de l'OS. Vous pouvez suivre l'état d'avancement globale de la tâche à l'aide de l'appel suivant :
```suggestion
`123456789` correspond à l'identifiant de la tâche d'installation de l'OS. Vous pouvez suivre l'état d'avancement global de la tâche à l'aide de l'appel suivant :
```

2024-02-02 18:23 UTC, JayBeeDe commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.fr-fr.md
> +Certains OS peuvent avoir une liste de questions spécifiques. Si c'est le cas, l'attribut `inputs`{.action} contient une liste de questions.
ok je fais ça

2024-02-06 14:46 UTC, sbraz approved these changes

2024-02-07 10:21 UTC, JayBeeDe commented on pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-gb.md
>  updated: 2024-02-07
```suggestion
updated: 2024-02-12
```

2024-03-04 10:12 UTC, merged

2024-03-04 10:12 UTC, OVH-Team-Guides commented
Thank you for your contribution @JayBeeDe