fix(byolinux): add information about "only one partition in the sourc…
ovh/docs pull request #5777
Opened 2024-02-09 08:37 UTC by ashmonger

…e image"

2024-02-09 10:48 UTC, sbraz requested changes

2024-02-09 10:48 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.en-gb.md
> +- An executable script `/root/.ovh/make_image_bootable.sh`, which reinstall and configure GRUB [example](https://github.com/ovh/bringyourownlinux/blob/main/example_build/files/make_image_bootable.shh
```suggestion
- An executable script `/root/.ovh/make_image_bootable.sh`, which will install or configure the bootloader, [for example GRUB](https://github.com/ovh/bringyourownlinux/blob/main/example_build/files/make_image_bootable.shhttps://github.com/ovh/bringyourownlinux/blob/main/example_build/files/make_image_bootable.sh)
```

2024-02-09 10:48 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.fr-fr.md
> +- Un script `/root/.ovh/make_image_bootable.sh` executable, qui réinstalle et configure GRUB [exemple](https://github.com/ovh/bringyourownlinux/blob/main/example_build/files/make_image_bootable.shhtt
```suggestion
- Un script `/root/.ovh/make_image_bootable.sh` exécutable, qui installera ou configurera le bootloader, [par exemple GRUB](https://github.com/ovh/bringyourownlinux/blob/main/example_build/files/make_image_bootable.shhttps://github.com/ovh/bringyourownlinux/blob/main/example_build/files/make_image_bootable.sh)
```

2024-02-09 10:48 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.en-gb.md
> +- Only ONE partition in the qcow2 image
```suggestion
- Only one partition in the qcow2 image
```
Tu mets pas de caps en anglais

2024-02-09 11:15 UTC, sbraz requested changes

2024-02-09 11:15 UTC, sbraz commented on pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.fr-fr.md
> +- Un script `/root/.ovh/make_image_bootable.sh` exécutable, qui installera ou configurera et configure le bootloader, [par exemple GRUB](https://github.com/ovh/bringyourownlinux/blob/main/example_bui
```suggestion
- Un script `/root/.ovh/make_image_bootable.sh` exécutable, qui installera ou configurera le bootloader, [par exemple GRUB](https://github.com/ovh/bringyourownlinux/blob/main/example_build/files/make_image_bootable.shhttps://github.com/ovh/bringyourownlinux/blob/main/example_build/files/make_image_bootable.sh)
```

2024-02-13 20:17 UTC, sbraz approved these changes

2024-02-14 08:04 UTC, merged

2024-02-14 08:04 UTC, OVH-Team-Guides commented
Thank you for your contribution @ashmonger