S3 Object Storage - Asynchronous Replication - New guide
ovh/docs pull request #6017
Opened 2024-03-22 15:54 UTC by OVH-Team-Guides

Replacing PR #5991

2024-03-26 14:46 UTC, lason-ovh requested changes
cf comment

2024-03-26 14:46 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +| Role                    | OVHcloud IAM role needed to allow OVHcloud Object Storage to access data from the source bucket & write data to destination buckets. Currently, OVHcloud has set a unique r
replace "replicationRole" by "s3-replication"

2024-03-27 12:58 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +  "Role": "string",
feedbacks from dev team: replace "string" in "role" attribute by "arn:aws:iam::<your_project_id>:role/s3-replication"

2024-03-27 13:00 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +        "Bucket": "string",
feedbacks from dev team; replace "string" in "Bucket" attribute by "arn:aws:s3:::<your_bucket_name>"

2024-03-27 13:01 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +  "Role": "string",
feedbacks from dev team: replace "string" in "role" attribute by "arn:aws:iam::<your_project_id>:role/s3-replication"

2024-03-27 13:02 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +  "Role": "IAM-role-ARN",
feedbacks from dev team: replace "string" in "role" attribute by "arn:aws:iam::<your_project_id>:role/s3-replication"

2024-03-27 13:08 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +      "Status": "Enabled",
attribute table should be respected to stay coherent: 
- add "Priority": 1
- add "Filter": { }
- add "DeleteMarkerReplication": { "Status": "Disabled" }

2024-03-27 13:09 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +  "Role": "IAM-role-ARN",
replace "IAM-role-ARN" in "role" attribute by "arn:aws:iam::<your_project_id>:role/s3-replication"

2024-03-27 13:09 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +      "Status": "Enabled",
add "Priority": 1

2024-03-27 13:10 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +  "Role": "IAM-role-ARN",
replace "string" in "role" attribute by "arn:aws:iam::<your_project_id>:role/s3-replication"

2024-03-27 13:11 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +      "ID": "rule1",
add "Priority" : 1  and "Filter": { }

2024-03-27 13:12 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +      "ID": "rule2",
add "Priority" : 2 and "Filter" : { }

2024-03-27 13:13 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +  "Role": "IAM-role-ARN",
replace "IAM-role-ARN" by "arn:aws:iam::<your_project_id>:role/s3-replication"

2024-03-27 13:14 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +      "Status": "Enabled",
add "Priority": 1

2024-03-27 13:15 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +      "Status": "Enabled",
add "Priority": 2

2024-03-27 13:15 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +      "ID": "replication-rule-456",
add "Priority": 1

2024-03-27 13:19 UTC, lason-ovh requested changes
added feedbacks from devs: json examples are not coherent from one example to another
- "role" is confusing from one example to another
- "destination" is confusing from one example to another

other feedbacks:
"la doc en FR ne s'affiche pas correctement alors que celle en EN s'affiche correctement. Principalement au niveau des tableaux de paramètres qui sont lisibles en EN et pas du tout en FR."

2024-03-27 13:28 UTC, OVH-Team-Guides commented
@lason-ovh : please share with dev teams that the FR version has not yet been proodfread.

2024-03-27 15:20 UTC, OVH-Team-Guides commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +- **Replicate data to a different region**
```suggestion
- **Replicate data to two different regions**
```

2024-03-27 15:42 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +      "Status": "Enabled",
add "ID": "ruleId"

2024-03-27 15:43 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +      }
add "DeleteMarkerReplication": { "Status": "Disabled" }

2024-03-27 15:43 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +      }
add "DeleteMarkerReplication": { "Status": "Disabled" }

2024-03-27 15:44 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +| StorageClass            | The target storage class: "STANDARD" for S3 Standard and "HIGH_PERF" for S3 High Performance.                            | No       |
delete "StorageClass" row because feature is not supported yet

2024-03-27 15:45 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +        "StorageClass": "STANDARD"|"HIGH_PERF"
delete "StorageClass" attribute because feature is not supported yet

2024-03-27 16:08 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +The replication status can be used to determine the status of an object that is being replicated. When you request a source object (using `GET object`) or source object metadata (using `HEAD object`)
feedbacks dev: supprimer la phrase "when you request.... replication-status" par "To get the replication status of an object, you can use the head-object command via the aws cli:
```bash
$ aws s3api head-object --bucket <source_bucket> --key <object_name>
{
   "LastMoodified" : "Fri, 15 Mar 2024 10:18:15 GMT",
   "ContentLength": 3481,
   "Etag": "\"417947d3634d4645e05ca9e875f5b202\"",
   "VersionId": "17104978950.04081",
   "ContentType": "binary/octet-stream",
   "Metadata": { },
   "StorageClass": "STANDARD",
   "ReplicationStatus": "COMPLETED"
}
```

2024-03-27 16:08 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +The `x-amz-replication-status` can have the following values:
replace "x-amz-replication-status" by "ReplicationStatus attribute"

2024-03-27 16:09 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +> When you replicate objects to multiple destination buckets, the value of `x-amz-replication-status` is "*COMPLETED*" only when the source object has been successfully replicated to all the destinat
replace "x-amz-replication-status" by "ReplicationStatus"

2024-03-27 16:09 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +> If one or more destination fail replication, the value of the header becomes "*FAILED*".
replace "header" by "attribute"

2024-03-27 16:10 UTC, lason-ovh requested changes
other feedbacks: use only aws cli to get replication status, do not mention the api

2024-03-29 11:20 UTC, OVH-Team-Guides commented
@lason-ovh & @KebirHakim , is the technical review now fully done on EN version?
Our proofreading is usually done after this tech review.

2024-03-29 15:41 UTC, lason-ovh commented on pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
> +| Objects encrypted with customer provided keys (SSE-C)        | Objects that have already been replicated to a previous destination |
petite erreur dans la doc: supprimer la ligne "Objects encrypted with customer provided keys (SSE-C)" dans la colonne "What is replicated" car cette feature n'est pas encore supportée

2024-03-29 15:42 UTC, lason-ovh requested changes
last review: delete unsupported feature in column "what is replicated"

2024-04-02 13:06 UTC, merged

2024-04-02 13:06 UTC, OVH-Team-Guides commented
Thank you for your contribution @KebirHakim