Add new guide about installing and using Falco on OVHcloud MKS
ovh/docs pull request #6078
Opened 2024-04-03 12:49 UTC by scraly

2024-04-03 13:10 UTC, titimoby requested changes
just a typo/writing review. I didn't run commands.

2024-04-03 13:10 UTC, titimoby commented on pages/public_cloud/containers_orchestration/managed_kubernetes/runtime-security-falco/guide.en-gb.md
> +As you can see we install also Falcosidekick thaks to several flags:
```suggestion
As you can see we install also Falcosidekick thanks to several flags:
```

2024-04-03 15:57 UTC, scraly commented
The PR is ready for proofreading 😊

2024-04-03 16:39 UTC, OVH-Team-Guides commented
Hello @scraly , please check my edition

2024-04-03 17:40 UTC, scraly commented
Hi @Y0Coss it's ok for me except one thing:
Why modifing `**` to `*-`? (the goal was to bold the word)
<img width="996" alt="image" src="https://github.com/ovh/docs/assets/2543381/656a826c-d81a-4b80-a10c-006652985a9c">

2024-04-04 07:01 UTC, OVH-Team-Guides commented
That's a bad search & replace on my side @scraly , I'll fix this

2024-04-04 07:15 UTC, scraly commented
Top thanks

2024-04-04 07:16 UTC, merged

2024-04-04 07:17 UTC, OVH-Team-Guides commented
Thank you for your contribution @scraly