MKS - Forwarding audit logs to LDP - Adding screenshots
ovh/docs pull request #6260
Opened 2024-05-02 14:29 UTC by KebirHakim

add pic new screen shot

2024-05-03 14:54 UTC, tcpdumpfbacke requested changes
-Adjust image size to max 1400px width
-Use standard color for highlighting (ff9803)

2024-05-06 07:05 UTC, OVH-Team-Guides commented
Hello @KebirHakim 
On top of requested changes by @tcpdumpfbacke , these screenshots also need to be linked into the guides actual content.

2024-05-07 11:45 UTC, OVH-Team-Guides approved these changes

2024-05-07 11:45 UTC, merged

2024-05-07 11:45 UTC, OVH-Team-Guides commented
Thank you for your contribution @KebirHakim