VCD [SK-1520] : Backup with Veeam on VCD guides
ovh/docs pull request #6284
Opened 2024-05-14 07:26 UTC by pg-ovh

First draft for Veeam backup on VCD

2024-05-16 16:19 UTC, OVH-Team-Guides requested changes
Please consider rewriting the part between line 84 and line 97

2024-05-16 16:19 UTC, OVH-Team-Guides commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.fr-fr.md
> +<!--- proofread stops below this point --->
This part (from line 84 to line 97 can't be proofread by our team.
The information is confusing (the different options/repository/storage offers lack descriptions) and the tone (especially the use of "je") is not appropriate.

2024-05-16 16:19 UTC, OVH-Team-Guides commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.fr-fr.md
> +> Pour pouvoir ajouter un job depuis la console VCD sur une VM, un JOB doit être pre ????
Incomplete sentence.

2024-05-21 15:16 UTC, franckcosta reviewed
can you check @pg-ovh  ?

2024-05-21 15:16 UTC, franckcosta commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.fr-fr.md
> +- Posséder une offre [Hosted Private cloud](https://www.ovhcloud.com/fr/enterprise/products/hosted-private-cloud/){.external}.
we need to remove this

2024-05-21 15:16 UTC, franckcosta commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.fr-fr.md
> +Veeam Backup & Replication accompagne VCD.
Veeam Data Platform

2024-05-21 15:16 UTC, franckcosta commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.fr-fr.md
> +Avec l'offre que vous avez souscrite vous disposer de 3 depots avec 2 Jobs configurés par défaut avec un quota de 100GB :
pas de Job configurés finalement.  
Pas de quota non plus.

2024-05-21 15:16 UTC, franckcosta commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.fr-fr.md
> +2. **Silver Repository** : STD Stockage Objet + Sauvegarde hors Site (Offsite)
Copy de sauvegarde hors site ( offsite ).

2024-05-21 15:16 UTC, franckcosta commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.fr-fr.md
> +3. **Gold Repository** : Haute performance stockage object + Sauvegarde hors site (offsite) + 14 points d'immutabilité (14 points de restaurations sur 2 sites différents)
Copie de sauvegarde hors site (offsite)

2024-05-21 15:16 UTC, franckcosta commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.fr-fr.md
> +Les référentiels sont tous configurés avec l'Object Storage Standard. Seul le produit de disponibilité générale répond aux spécifications de référentiel indiquées.
to remove

2024-05-21 16:18 UTC, pg-ovh commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.fr-fr.md
> +3. **Gold Repository** : Haute performance stockage object + Sauvegarde hors site (offsite) + 14 points d'immutabilité (14 points de restaurations sur 2 sites différents)
Comme ça : 
Par défaut, vous avez **les dépots** suivant :
1. **Bronze Repository** : STD Stockage Objet
2. **Silver Repository** : STD Stockage Objet + Copie de sauvegarde hors site ( offsite ).
3. **Gold Repository** : Haute performance stockage object + Copie de sauvegarde hors site (offsite)

2024-05-22 08:59 UTC, pg-ovh commented
Hello @OVH-Team-Guides I have added your review. I have not included a table of content since you do not recommend it in general, but I would consider it in this guide.

2024-05-22 16:34 UTC, pg-ovh reviewed
Ok for me.

2024-05-23 07:57 UTC, OVH-Team-Guides approved these changes

2024-05-23 07:57 UTC, merged

2024-05-23 07:57 UTC, OVH-Team-Guides commented
Thank you for your contribution @pg-ovh