Hk network private network
ovh/docs pull request #6478
Opened 2024-06-21 16:43 UTC by KebirHakim

How to share a private network between 2 public cloud projects

2024-06-24 12:51 UTC, OVH-Team-Guides requested changes
A guide folder can only contain files named as `guide.language.md` so please delete the `Share_Private_Network` file or rename it.

The guide folder name contains empty spaces, which can't be accepted.

As this is a new guide, you should create a meta.yaml file and edit the index file.

You also have to write the fr-fr version of the guide.

2024-06-24 12:51 UTC, OVH-Team-Guides commented on pages/network/Share Private Network/guide.en-gb.md
> +## Capabilities and limitations
This section is either empty and needs to be poupulated OR should be deleted

2024-06-24 12:51 UTC, OVH-Team-Guides commented on pages/network/Share Private Network/guide.en-gb.md
> +### Prerequisites
Wrong term (Requirements) and markdown hierarchy (use an H2)

2024-06-24 12:51 UTC, OVH-Team-Guides commented on pages/network/Share Private Network/guide.en-gb.md
> +### Procedure
Wrong term (Instructions) and markdown hierarchy (use an H2 then adapt your hierarchy from it)

2024-06-24 12:51 UTC, OVH-Team-Guides commented on pages/network/Share Private Network/guide.en-gb.md
> +#### On our first project
To rephrase

2024-06-24 12:51 UTC, OVH-Team-Guides commented on pages/network/Share Private Network/guide.en-gb.md
> +1. List the project IDs:
Please skip a line after/before each code snippet

2024-06-24 12:51 UTC, OVH-Team-Guides commented on pages/network/Share Private Network/guide.en-gb.md
> +On our second (or more) project :
missing markdown title

2024-07-19 15:36 UTC, KebirHakim commented
i create a new PR

2024-07-19 15:36 UTC, closed without merging