PGA - HPC : 2 new VCD guides Networking - concepts + components creation
ovh/docs pull request #6490
Opened 2024-06-25 15:16 UTC by pg-ovh

2024-07-01 10:50 UTC, OVH-Team-Guides requested changes

2024-07-01 10:50 UTC, OVH-Team-Guides commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.fr-fr.md
> +- Guide 3 : [« VMware Cloud Director on OVHcloud - Network - Comment créer un tunnel IPsec avec VCD on OVHcloud ? »](/pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_ips
This comment applies for both versions (FR + EN):

These links (guides 3 4 5) target some guides which do not yet exist and would create 404s on prod. 
So you need to either add the guides in the same PR **or** delete this section from this guide (until all guides are prodded) **or** withdraw the second part of each link to replace it with a "Coming soon" wording.

2024-07-01 10:50 UTC, OVH-Team-Guides commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.fr-fr.md
> +- [Bloc IP - Gérer et configurer un bloc IP /29](/pages/web_cloud/internet/internet_access/comment_commander_et_gerer_un_bloc_ip_29).
How are these 2 guides related to the current topic? Is it random picking?

2024-07-01 10:50 UTC, OVH-Team-Guides commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.fr-fr.md
> +Nous allons maintenant créer une **Passerelle Edge** pour que notre espace IP puisse être accédé depuis le réseau privé que nous allons créer dans la partie 3 de ce guide.
we already are in step 3, is this logical?

2024-07-01 10:50 UTC, OVH-Team-Guides commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.fr-fr.md
> +Cela représente la passerelle précédemment créée.
To rephrase please as this sentence doesn't make any sense alone.

2024-07-01 10:50 UTC, OVH-Team-Guides commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.fr-fr.md
> +Une fois votre choix effectué (étape 3 : Création d'une Passerelle Edge), cliquez sur `SUIVANT`{.action}.
Why is the sentence in brackets here ? It is unclear

2024-07-01 10:50 UTC, OVH-Team-Guides commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.fr-fr.md
> +Sélectionnez **l'Organisation du Centre de Données Virtuel vDC** où le **Groupe de Centre de données** dans le scope avec lequel vous souhaitez créer votre réseau.
Looks like a verb is missing in this sentence. Or "où" should be "ou".

2024-07-01 10:50 UTC, OVH-Team-Guides commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.en-gb.md
> +Go to the Networking section by clicking: `Mise en réseaux | Réseaux`{.action}.
FR text to replace with actual EN menus.

2024-07-01 10:50 UTC, OVH-Team-Guides commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.en-gb.md
> +Select **the vDC Virtual Datacenter Organization** where the **Datacenter Group** in the scope with which you want to create your network.
Looks like a verb is missing.

2024-07-01 10:51 UTC, OVH-Team-Guides commented
Please DO NOT revert changes which have been made on the files. 
Aside from all the comments above, some links to guides which don't exist yet have to be deleted or replaced before this Pull Request can be considered as valid.

2024-07-01 13:21 UTC, pg-ovh commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.fr-fr.md
> +- [Bloc IP - Gérer et configurer un bloc IP /29](/pages/web_cloud/internet/internet_access/comment_commander_et_gerer_un_bloc_ip_29).
It is related to overall network concept, which help with the understanding. I understand it would be better to have one dedicated to HPC, but there is not one yet. Should I remove them @OVH-Team-Guides ?

2024-07-01 13:28 UTC, OVH-Team-Guides commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.fr-fr.md
> +- [Bloc IP - Gérer et configurer un bloc IP /29](/pages/web_cloud/internet/internet_access/comment_commander_et_gerer_un_bloc_ip_29).
Then I suggest using only this link which details our Network solutions https://www.ovhcloud.com/fr/network/

2024-07-01 14:27 UTC, pg-ovh commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.fr-fr.md
> +Nous allons maintenant créer une **Passerelle Edge** pour que notre espace IP puisse être accédé depuis le réseau privé que nous allons créer dans la partie 3 de ce guide.
I was relating to the sub part 3.

2024-07-01 14:33 UTC, pg-ovh commented
Thanks for your help @OVH-Team-Guides, let me know if there is anything else I missed :+1:

2024-07-02 08:55 UTC, OVH-Team-Guides commented
@pg-ovh , here are best practices for your upcoming productions:
- The index entries can’t contain `/pages/` in the links.
- Please reserve the ``button`{.action}` format to highlight clickable buttons in interfaces. Do not apply it for variables such as IPs, names examples, etc.
- In English, there is no empty space before a `:` or a `?`. It’s the contrary for French.
- The now only accepted community introduction sentences are:
    - FR: `Échangez avec notre [communauté d'utilisateurs](/links/community).`
    - EN: `Join our [community of users](/links/community).`

2024-07-02 08:56 UTC, OVH-Team-Guides approved these changes

2024-07-02 08:56 UTC, merged

2024-07-02 08:56 UTC, OVH-Team-Guides commented
Thank you for your contribution @pg-ovh