Add Guide: Obtaining Source IP in Octavia on OVHcloud without Kubernetes CCM
ovh/docs pull request #6704
Opened 2024-08-07 11:28 UTC by KebirHakim

2024-08-07 12:20 UTC, Y0Coss commented
@KebirHakim , you can delete the fr-fr file. All the K8S documentation is only available in English.

2024-08-08 13:05 UTC, scraly commented
General remark: Octavia is the technology created by Openstack, but the product used is Public Cloud Load Balancer :)

2024-08-08 13:17 UTC, scraly commented
Second remark: 
<img width="761" alt="image" src="https://github.com/user-attachments/assets/0be3995b-ff37-4300-b204-4b9cc74d68d3">

Why the name contains "proxy protocol"? Is it a wrong copy/paste?
I think it can be better to name the folder accrding to the goal of the guide: public-cloud-load-balancer-source-ip (it can be an idea for example)

the name of the folder should be aso fixed in index.md file.

2024-08-08 13:20 UTC, scraly requested changes

2024-08-08 13:20 UTC, scraly commented on pages/index.md
> +                + [Obtaining Source IP in Octavia](public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_proxy_protocol)
```suggestion
                + [Obtaining Source IP in Public Cloud Load Balancer](public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_proxy_protocol)
```

2024-08-08 13:20 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +title: 'Obtaining Source IP in Octavia'
```suggestion
title: 'Obtaining Source IP in Public Cloud Load Balancer'
```

2024-08-08 13:20 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +excerpt: 'Learn how to configure Octavia to obtain the client source IP in the context of OVHcloud without using Kubernetes CCM.'
```suggestion
excerpt: 'Learn how to configure Public Cloud Load Balancer to obtain the client source IP in the context of OVHcloud without using Kubernetes CCM.'
```

2024-08-08 13:20 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +**This guide explains how to configure Octavia to obtain the client source IP in the context of OVHcloud without using Kubernetes CCM.**
```suggestion
**This guide explains how to configure Public Cloud Load Balancer to obtain the client source IP in the context of OVHcloud without using Kubernetes CCM.**
```

2024-08-08 13:20 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +Create an instance on OVHcloud and install a web server that will serve as the backend. For example, we will use an NGINX server.
```suggestion
In this guide you will create an instance on OVHcloud and install a web server (NGINX) that will serve as the backend.
```

2024-08-08 13:20 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +
remove blank lines

2024-08-08 13:20 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +#### 1. Create the Octavia LoadBalancer
```suggestion
#### 1. Create the Public Cloud Load Balancer
```

2024-08-08 13:20 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +
```suggestion

The Public Cloud Load Balancer (based on Octavia OpenStack project) provides a lot of features.

```

2024-08-08 13:20 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +- Access to an OpenStack environment on OVHcloud with Octavia configured.
```suggestion
- Access to an OpenStack environment on OVHcloud with a Public Cloud Load Balancer configured.
```

2024-08-08 13:20 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +Access the OpenStack interface on OVHcloud, then create a LoadBalancer:
```suggestion
Access the OpenStack interface on OVHcloud, then create a Public Cloud LoadBalancer:
```

2024-08-09 12:00 UTC, scraly requested changes
I add few suggestions

2024-08-09 12:49 UTC, scraly requested changes
my suggestions
thanks! :)

2024-08-09 12:49 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +- Access to an OpenStack environment on OVHcloud with Octavia configured.
Good practice: add a link to an existing guide

2024-08-09 12:49 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +- Administrative rights to create and modify LoadBalancer services.
TODO: precise which rights and where? ^^

2024-08-09 12:49 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +#### 1. Create an instance on OVHcloud
```suggestion
#### 1. Create an OVHcloud Public Cloud Instance
```

2024-08-09 12:49 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +Access your [OVHcloud Control Panel](/links/manager), go to the "Public Cloud" section and create a new instance. For detailed instructions, see the official documentation: [Creating an instance on O
Precise which menu? (instances)

2024-08-09 12:49 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +Connect to the instance via SSH
```suggestion
Connect to the instance via SSH.
```

2024-08-09 12:49 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +Connect to the instance via SSH
Add the command.

2024-08-09 12:49 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +sudo dnf install -y nginx
Check if this comand is working on all of the compute instances OS.
If not, precise the command for the OS.

2024-08-09 12:49 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +sudo nano /etc/nginx/nginx.conf
Check the tool to use to keep consistency/homogeous (emacs, vi, nano...).

2024-08-09 12:49 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +```nginx
nginx if it's working, else bash

2024-08-09 12:49 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +    http {
remove useless lines

2024-08-09 12:49 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +#### 3. Add members to the pool (the backend instances)
Add in requierements sections: create 2 instances

2024-08-09 12:49 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +#### 1. Get the VIP address of the LoadBalancer
we can precise what is VIP ;)

2024-08-09 12:49 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +curl http://192.168.0.57
example:

curl $VIP_ADDRESS

2024-08-09 12:49 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +openstack loadbalancer show my-loadbalancer -c vip_address -f value
example: 

VIP_ADDRESS=$(openstack loadbalancer show my-loadbalancer -c vip_address -f value)
echo $VIP_ADDRESS

2024-08-09 12:49 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_Proxy_Protocol/guide.en-gb.md
> +- [Managing subnets in OpenStack](https://docs.openstack.org/neutron/latest/admin/deploy-ovs-selfservice.html){.external}.
It could be better if we can add a link to our guides

2024-08-23 06:54 UTC, Y0Coss commented on pages/index.md
> +                + [Obtaining Source IP in Octavia](public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_proxy_protocol)
Why is this guide in the /managed-kubernetes/ folder and now located under the Compute category in the index?
Shouldn't it be physically relocated in the `public_cloud/public_cloud_network_services` folder and under the `[Technical resources](public-cloud-network-technical-resources)` category (from line 662) in the index?

2024-08-23 06:55 UTC, Y0Coss commented on pages/index.md
> +                + [Obtaining Source IP in Octavia](public_cloud/containers_orchestration/managed_kubernetes/Octavia_Tutorial_Add_proxy_protocol)
@yomovh , any opinion on the right index location for this new guide?

2024-09-05 08:23 UTC, Y0Coss requested changes
Before the Guides Team can review this content, you need to align/fix the following:

- guide folder location: /managed_kubernetes/
VS
- guide index location: /compute/

- guide title: "Obtaining Source IP in Public Cloud Load Balancer"
VS
- guide folder naming: Octavia_Tutorial_Add_Proxy_Protocol
- guide full_slug: public-cloud-managed-kubernetes-octavia-tutorial-add-proxy-protocol

2024-11-04 07:53 UTC, Y0Coss commented
@scraly, @antonin-a 
I'm closing this Pull Request as too much work is needed to make it compliant for a merge.
I'm not deleting the branch so that content can still be extracted if need be. Thanks

2024-11-04 07:53 UTC, closed without merging