HPC : Guide update life cycle policy
ovh/docs pull request #6716
Opened 2024-08-08 07:58 UTC by pg-ovh

2024-08-08 10:22 UTC, Y0Coss requested changes

2024-08-08 10:22 UTC, Y0Coss commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-gb.md
> +OVHcloud has a lifecycle policy for the service in order to take into account several factors, such as :
There is no space in English before punctuation signs. Please revert this change on lines 18, 21, 22, 129 for all guides except fr-fr and fr-ca.

2024-08-08 10:22 UTC, Y0Coss commented on pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-gb.md
> +Join our [community of users](/links/manager).
wrong link on all versions except fr-fr and fr-ca
It should be `(/links/community)`

2024-08-08 15:42 UTC, Y0Coss approved these changes

2024-08-08 15:44 UTC, Y0Coss commented
Waiting for the review from @franckcosta to merge the PR.
**Note**: I'd recommend switching the dates format to the international format YYYY-MM-DD

2024-08-08 16:52 UTC, pg-ovh commented
Thanks @Y0Coss it's all good with @franckcosta. I'll add the good date format.

2024-08-09 07:53 UTC, merged

2024-08-09 07:53 UTC, Y0Coss commented
Thank you @pg-ovh for your contribution