fix(backing-up-cluster-with-velero): disable checksumAlgorithm
ovh/docs pull request #6857
Opened 2024-09-11 09:24 UTC by Cogitri

Starting with Version 1.9.2 of the velero-aws plugin, `checksumAlgorithm` is set to CRC32, which OVH doesn't support. As such, without disabling it, backups fail due to invalid parameters being sent to OVH.

2024-09-13 14:05 UTC, scraly requested changes
Thanks, yes indeed since 1.9.2 of https://github.com/vmware-tanzu/velero-plugin-for-aws/ this field is required.

By the way, you should need to update the version of the plugin too (to the latest one at the moment).

2024-09-13 14:05 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/backing-up-cluster-with-velero/guide.en-us.md
>    --plugins velero/velero-plugin-for-aws:v1.6.0,velero/velero-plugin-for-csi:v0.4.0 \
```suggestion
  --plugins velero/velero-plugin-for-aws:v1.10.1,velero/velero-plugin-for-csi:v0.4.0 \
```

2024-09-13 14:05 UTC, scraly commented on pages/public_cloud/containers_orchestration/managed_kubernetes/backing-up-cluster-with-velero/guide.en-us.md
>    --plugins velero/velero-plugin-for-aws:v1.6.0,velero/velero-plugin-for-csi:v0.4.0 \
```suggestion
  --plugins velero/velero-plugin-for-aws:v1.10.1,velero/velero-plugin-for-csi:v0.4.0 \
```

2024-09-25 15:08 UTC, merged

2024-09-25 15:09 UTC, Y0Coss commented
Thank you for your contribution @Cogitri