Update guide.en-us.md
ovh/docs pull request #7169
Opened 2024-11-15 07:01 UTC by btbenjamin

Add new annotation  : For Managed Kubernetes Service version >= 1.31

2024-11-15 09:06 UTC, Lucasgranet requested changes
Hello

Thank you for your contribution.

I made some reviews to let the user to chose the right annotation.
Currently, a MKS cluster < 1.31 can deploy an Octavia LoadBalancer (using the right annotation to select between "LoadBalancer for K8S" or "Octavia").

2024-11-15 09:06 UTC, Lucasgranet commented on pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.en-us.md
> +      # For Managed Kubernetes Service version < 1.31
```suggestion
      # For K8S service based on "Loadbalancer for K8S" (default LB provisioned with MKS < 1.31)
```

2024-11-15 09:06 UTC, Lucasgranet commented on pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.en-us.md
> +      # For Managed Kubernetes Service version >= 1.31
```suggestion
      # For K8S service based on the Octavia implementation (default LB provisioned with MKS >=1.31)
```

2024-11-15 09:06 UTC, Lucasgranet commented on pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.en-us.md
> +      # For Managed Kubernetes Service version < 1.31
```suggestion
      # For K8S service based on "Loadbalancer for K8S" (default LB provisioned with MKS < 1.31)
```

2024-11-15 09:06 UTC, Lucasgranet commented on pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.en-us.md
> +      # For Managed Kubernetes Service version < 1.31
```suggestion
      # For K8S service based on "Loadbalancer for K8S" (default LB provisioned with MKS < 1.31)
```

2024-11-15 09:06 UTC, Lucasgranet commented on pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.en-us.md
> +      # For Managed Kubernetes Service version >= 1.31
```suggestion
      # For K8S service based on the Octavia implementation (default LB provisioned with MKS >=1.31)
```

2024-11-15 09:06 UTC, Lucasgranet commented on pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.en-us.md
> +      # For Managed Kubernetes Service version >= 1.31
```suggestion
      # For K8S service based on the Octavia implementation (default LB provisioned with MKS >=1.31)
```

2024-11-15 09:12 UTC, btbenjamin commented
Hello @Lucasgranet ,

Thanks for your review !
I suggest to add this card too :

![image](https://github.com/user-attachments/assets/9fb7bfcc-3636-47fe-9951-782618fd34fc)

2024-11-18 15:24 UTC, Y0Coss approved these changes

2024-11-18 15:30 UTC, Lucasgranet approved these changes

2024-11-18 15:30 UTC, merged

2024-11-18 15:30 UTC, Y0Coss commented
Thank you for your contribution @btbenjamin